### ISSUE TITLE
「第六章」代码清单6-36的一点建议

### ISSUE THREAD

**Issue by iduanyingjie** [ZhangHanDong/tao-of-rust-codes#101]
# 页码与行数

- 第182页
- 第1行至第13行

---

1.
在定义c的时候，其实可以给c手动设定它的类型，可以是Fn，也可以是FnOnce，例如：
```rust
let c: impl Fn() = move || { println!("{:?}", s) };
let c: impl FnOnce() = move || { println!("{:?}", s) };
```

2.
在书中的代码清单中闭包c中的代码只是打印了s的值，但是如果不是打印s的值，而是直接返回s（s的所有权又从闭包中转移出来了），那么c它的类型就是FnOnce了，c就不能再执行多次。
```rust
let c = move || s;
```

**Comment by ZhangHanDong** [comment]
@iduanyingjie 感谢建议，回头讨论

**Comment by ZhangHanDong** [comment]
@iduanyingjie 感谢你的建议。这些就留给读者自行探索吧。
