### ISSUE TITLE
第二章 语言精要

### ISSUE THREAD

**Issue by larkliu** [ZhangHanDong/tao-of-rust-codes#102]
# 页码与行数
P16 代码清单2-5 line7，编译器并不会产生错误，虽然产生了move。
# 文本或排版错误
后面的描述写：“代码编译执行以后....，编译器提示"other value used after move"”，感觉这句话不太恰当：因为首先代码是能够编译过的，而且能执行，所以即使此时能够提示错误也不是编译器提示的（虽然没有产生）。

**Comment by ZhangHanDong** [comment]
@larkliu  感谢反馈。

这个问题已经有人勘误过了。参考 [https://github.com/ZhangHanDong/tao-of-rust-codes/issues/14 ](https://github.com/ZhangHanDong/tao-of-rust-codes/issues/14 )

另外，请参考随书源码的示例。
