### ISSUE TITLE
[第四章] 4.2.4  文字错误

### ISSUE THREAD

**Issue by MILIFIRE** [ZhangHanDong/tao-of-rust-codes#105]
# 页码与行数

- 第115页
- 第24行

---

# 文本错误

> 对于基本原生数据类型来说，Rust 是默认将其分配到栈中。那么，结构体(Enum) 或 联合体 (Union)
是被分配到哪的呢？

> 结构体英文应该是(Struct)

**Comment by ZhangHanDong** [comment]
感谢反馈 @MILIFIRE
