### ISSUE TITLE
[第三章] 52页，编译期检查数组越界说法不准确

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#107]
# 页码与行数

- 第52页
> C和C++编译期并不检查数组是否会越界访问
> Rust 语言在编译期就能检查数组是否越界访问

只有数组下标为常量的情况下，才能编译期检查访问越界。下标变量的情况编译期不可能做到检查越界。

|     语言\能否编译期检查           |下标常量   |  下标为变量|
|  ---  |  ---  |  --- | 
|   C/C++    |    能 |     不能   |
|Rust|    能 |   不能 |

编译期越界检查方面Rust和C/C++的能力是一样的。

**Comment by ZhangHanDong** [comment]
相关资料引用

- [https://internals.rust-lang.org/t/make-index-out-of-bounds-a-compile-time-error/3489](https://internals.rust-lang.org/t/make-index-out-of-bounds-a-compile-time-error/3489)
- [https://stackoverflow.com/questions/28389371/why-does-rust-check-array-bounds-at-runtime-when-most-other-checks-occur-at-c](https://stackoverflow.com/questions/28389371/why-does-rust-check-array-bounds-at-runtime-when-most-other-checks-occur-at-c)
