### ISSUE TITLE
[第三章] 52页，”也可将对象看作类型“表意不清

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#108]
# 页码与行数

- 第52页
> 实际上，也可将对象看作类型

看得有点不知道啥意思，可能是想说”也可以通过检查对象是否满足某些特征的方式来代替检查类型“？

> Ruby和Python语言中，对象之间通过消息进行通信

Python的叫法是调用方法，不叫发消息。Python解释器里面对应的C函数的命名也是叫call，不叫send。

**Comment by ZhangHanDong** [comment]
@kvinwang  是「代替类型检查」的意思，我再修正下。

「调用方法」在oop模型里也叫「对象间消息传递」，不一定非得用send才叫发消息。

**Comment by kvinwang** [comment]
> oop模型里也叫「对象间消息传递」

OOP里面这么叫没错，所以我才说的Python里面"不叫"发消息，而不是说”不是"发消息。
OOP  != Python, 只有当用OOP的思维写程序的时候，才可以把Python里面的"调用"理解为"发消息"，笼统地这么称呼就不准确了。
如果这里强调的是OOP，那可以改为：“在OOP中，对象之间通过消息进行通信”，不用具体到语言。

**Comment by ZhangHanDong** [comment]
@kvinwang  Python不属于OOP语言吗

**Comment by kvinwang** [comment]
>  Python不属于OOP语言吗？

Python支持OOP，支持得很好。但不像Java那样和OOP绑得很死，它同Rust一样是支持多范式的。从标准库就可以看出有很大一部分东西不是OOP的。

如果是一篇博文，我就不会叫这个真了。 但对于技术书籍，我个人认为应该要严谨对待。

**Comment by ZhangHanDong** [comment]
@kvinwang  那就更改下措辞吧，主要是说oop模型。
