### ISSUE TITLE
[第十三章] 504-505页，ManuallyDrop为union描述需更新

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#110]
- 第504-505页

ManuallyDrop现在已经改为struct + lang item来实现，union相关描述需要更新

**Comment by ZhangHanDong** [comment]
书中关于ManuallyDrop之前的Union实现还继续保留，另外加一句说明，告诉读者Rust 1.32稳定版已经改为了结构体和Lang Item来实现。

之所以保留，也是为了多一份关于Union的知识点。
