### ISSUE TITLE
「第三章」`3.4.3 抽象类型` impl Trait 描述错误

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#111]
# 页码与行数

- 第 76 页
- 第 5 行

---

# 文本或排版错误

> 另外，impl Trait 只能用于为单个参数指定抽象类型，如果对多个参数使用 impl Trait 语法，编译器将报错

这里不太对，不是 **多个参数** 使用了 impl Trait 会报错，而是即便是相同的 Trait 签名，编译器也不认为是相同类型。下方代码清单 3-42 下的一段的解释是对的。

下面的代码就使用了多个 impl Trait，代码可正常编译和执行

```rust
use std::fmt::Display;
use std::ops::Add;

fn add_print<T>(a: impl Add<Output = T> + Display, b: impl Add<Output = T> + Display) {
    println!("{}", a);
    println!("{}", b);
}
fn main() {
    add_print(5, 6)
}
```

**Comment by ZhangHanDong** [comment]
@eZioPan  感谢反馈，确认后修正下

**Comment by ZhangHanDong** [comment]
@eZioPan 你在我的微信群吗？还是在社区qq群？可以私聊我一下，有惊喜。

**Comment by eZioPan** [comment]
@ZhangHanDong 我好像都没加，我是通过知乎搜索到您和这本书的的，不知道如何加入？

**Comment by ZhangHanDong** [comment]
@eZioPan  加我q吧，二四70二六六28

**Comment by eZioPan** [comment]
@ZhangHanDong 已经申请加好友啦
