### ISSUE TITLE
[第十三章] 508页，未初始化内存不会暴露出来的说法不准确

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#112]
示例中的未初始化内存在unwind的时候是会被暴露给safe rust访问到的，是不安全的。

**Comment by ZhangHanDong** [comment]
@kvinwang 感谢反馈

**Comment by ZhangHanDong** [comment]
@kvinwang 代码清单13-44中展示的未初始化内存风险，Rust是不会允许开发者catch_unwind的。

**Comment by kvinwang** [comment]
除了catch_unwind还有
impl Drop可以访问这些未初始化内存。

越是不轻易触发的UB，越是隐蔽难查，出问题往往到线上才发现，导致的后果越严重。这类问题是最可怕的，我们越是应当提醒用户小心处理此类问题，而不是朝着反方向给用户安慰说"不会轻易出问题"，因为这会导致读者掉以轻心更容易写出隐蔽bug。

**Comment by ZhangHanDong** [comment]
修改示例：

```rust
struct A(u32);

impl Drop for A {
    fn drop(&mut self) {
        println!("droping {} in A", self.0);
    }
}

unsafe fn panic_unsafe(x: &mut Vec<A>, a: A) {
    x.push(a);
    x.set_len(10);
    panic!("panic in unsafe block");
}

fn main(){
    let mut x = vec![];
    unsafe {
        // 该unsafe函数因为panic而暴露了未初始化内存
        panic_unsafe(&mut x, A(42))
    }
}
```

[play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fbdf3fc123d2de67508f0acb88d1e16b)
