### ISSUE TITLE
「第三章」`3.4.4 标签 trait` Sized trait 表述易混淆且名称少了一个字母

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#113]
# 页码与行数

- 第 78 页
- `Sized trait` 最后两段

---

# 文本或排版错误

> 但是动态大小类型不能随意使用……所以，当使用 `?Size` 限定时，应该想想这三条规则

---

`?Size` 末尾少了一个字母 d

---

如果我理解的没有错，本小节所说的 `动态大小类型`  应该专指 `Unsize` 吧。如果是这样，我建议把这两句改成：

- 但是 `Unsize` 限定的动态大小类型不能随便使用

- 所以，当使用 `Unsize` 限定和 `?Sized` 限定时，应该想想这三条规则。

整个段落里都没有给 `?Sized` 中文的名称，这里突然连续说了两个不一样的 trait 容易让人把 `?Size` 理解为 `动态大小类型` 限定

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈。

**Comment by ZhangHanDong** [comment]
@eZioPan  

-  「?Sized」,  内容中有阐述： “?Sized包含了Sized和Unsize两种限定”。
-  「动态大小类型」，内容中也有阐述：“Unsize标识的是动态大小类型”。
