### ISSUE TITLE
「第六章」代码清单 6-85 下方批注单词拼写错误

### ISSUE THREAD

**Issue by micooz** [ZhangHanDong/tao-of-rust-codes#115]
# 页码与行数

- 代码清单 6-85

---

# 文本或排版错误

> 最后一行单词 FromIberotor 应改为 FromIterator。

**Comment by ZhangHanDong** [comment]
@micooz  感谢反馈。 这个错的这么离谱。。。怀疑是排版人员使用了word的单词自动纠错功能。。。
