### ISSUE TITLE
[第六章]“对于数组来说，上限和下限的值是一样的”，这句话没能理解，求解惑

### ISSUE THREAD

**Issue by jonirrings** [ZhangHanDong/tao-of-rust-codes#118]
# 页码与行数

- 第199页
- 第29行前后

---

# 文本或排版错误

> 暂无

---

# 代码错误

> 暂无

### Rust版本

> 暂无

### 错误信息

> 暂无

如题，这句话没能理解，不知道是否看漏了什么信息，有劳解惑。

**Comment by ZhangHanDong** [comment]
@jonirrings 感谢反馈，稍后给你回复

**Comment by ZhangHanDong** [comment]
@jonirrings  刚才看了这个问题。你看漏了很多内容。注意图6-4展示的，以及图上方的多处说明，比如
「size_hint方法实际返回的是迭代器起点指针到终点指针的距离值」。
数组的size_hint的上下限都是一样的。
