### ISSUE TITLE
[第七章]216页“复合”一词是否使用错误？

### ISSUE THREAD

**Issue by jonirrings** [ZhangHanDong/tao-of-rust-codes#119]
# 页码与行数

- 第216页
- 倒数第2行

---

# 文本或排版错误

> “复合”->“组合”

---

# 代码错误

>无

### Rust版本

>无

### 错误信息

>无

“采用抽象和复合等手段来组织和复用代码。”
这里的确该使用“复合”么？

**Comment by ZhangHanDong** [comment]
@jonirrings 感谢反馈，我斟酌斟酌

**Comment by ZhangHanDong** [comment]
@jonirrings  刚看了下内容，上下文是函数式语言范式相关，所以用「复合」是合适的。
