### ISSUE TITLE
「第一章」锈菌是真菌，不是细菌

### ISSUE THREAD

**Issue by infinnie** [ZhangHanDong/tao-of-rust-codes#12]
# 页码与行数

- 第2页
- 第9行

---

# 文本或排版错误

> 像不像一个细菌？

锈菌是一种真菌，而真菌是真核生物，细菌是原核生物。实际上，真菌和动物的亲缘关系比他们和植物的更加接近。

**Comment by ChenYCL** [comment]
说的很好

**Comment by ZhangHanDong** [comment]
@infinnie 哈哈，感谢反馈

**Comment by yesqiao** [comment]
猜测作者的意思是说 Logo 像细胞

**Comment by ZhangHanDong** [comment]
@yesqiao  也不是。我以为细菌和真菌外形一样。。。
