### ISSUE TITLE
「第五章」 `5.5.2` 节 `省略生命周期参数` 中的错误 

### ISSUE THREAD

**Issue by knewbie** [ZhangHanDong/tao-of-rust-codes#121]
# 页码与行数

- P144
- 第2行 & 第4行

---

# 排版错误

>  11.  // 省略 应该跟在 12. 函数后
>  13. // 展开 应该跟在 14. 函数后

**Comment by ZhangHanDong** [comment]
@knewbie 感谢反馈，稍后确认下

**Comment by ZhangHanDong** [comment]
@knewbie 这个不是错误。这是版面放不下了，所以注释放到了代码上方而已。
