### ISSUE TITLE
第二章 语言精要 27页 浮点类型错误

### ISSUE THREAD

**Issue by xuxiaoyu2010** [ZhangHanDong/tao-of-rust-codes#122]
# 页码与行数

- 第27页
- 第8行

---

# 浮点类型错误

> f64， 单精度64位浮点数，...

---
查阅了相关资料，均说明 64位浮点数应为双精度浮点数。并且在rust官方文档中查到

> Floating-point numbers are represented according to the IEEE-754 standard. The f32 type is a single-precision float, and f64 has double precision.

[官方文档rustbook中 Datatypes](https://doc.rust-lang.org/book/ch03-02-data-types.html "rustbook")

因此f64为单精度浮点数是写错了吧？

**Comment by ZhangHanDong** [comment]
@xuxiaoyu2010 感谢反馈。估计是手误。
