### ISSUE TITLE
[第七章] 225页对 其它语言的Enum描述与事实不符

### ISSUE THREAD

**Issue by bonfy** [ZhangHanDong/tao-of-rust-codes#123]
# 页码与行数

- 第225页
- 最后一行

---
`诸如 Ruby、Python、Java、C++之类的面向对象语言会如何表示颜色。首先要定义一个Color类，也需要为具体的颜色定义相应的类`

觉得与事实不符，至少 Python 也是有 Enum 的，这么描述我觉得不太妥当

**Comment by ZhangHanDong** [comment]
@bonfy 感谢反馈。这里的描述，只是一种方案。当然实际开发中有很多方案，我不可能都表示出来。书里只是想突出Enum。

**Comment by kvinwang** [comment]
Python并没有语言层面支持enum。有库通过class模拟一些enum的特征，也并不完美，和语言级支持enum不是同一个东西

**Comment by ZhangHanDong** [comment]
修正：

加一条批注：

> 本书旨在说明Enum的便利性，不排除罗列的这些OOP语言也会有语言级或非语言级的Enum支持。
