### ISSUE TITLE
「第二章」`2.1.3 核心库` 核心库内容描述问题

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#124]
# 页码与行数

- 第 12 页
- 2.1.3 核心库

---

# 文本或排版错误

> 基本原始类型……

`bool` `tuple` `pointer` 是在 `Crate std` 中定义的

`array` 到目前为止(`Rust 1.32.0`)，还是 `[Experimental]` 的状态

> 常用功能型数据类型，满足常见的功能性需求……

这一段所列举的所有的数据类型都是 `Crate std` 中定义的

> 常见的宏定义……

`println!` 和 `vec!` 是 `Crate std` 中定义的

上面列的问题都是参照了 doc.rust-lang.org 的搜索结果发现的

**Comment by mzji** [comment]
`bool` 、 `tuple` 、 `* const T` 和 `* mut T` 、 `array` 这几种都算是原始类型，实际上标准库源码里是找不到它们的定义的，只能找到[相关文档](https://github.com/rust-lang/rust/blob/master/src/libstd/primitive_docs.rs)而已。
`println!()` 和 `vec!()` 确实不在核心库里，而是在标准库里。

**Comment by upsuper** [comment]
标准库基本上re-export了所有核心库定义的东西，所以core里面有的在std里有非常正常，也并非是“重复”。std和core在使用上基本上是互斥的。

**Comment by ZhangHanDong** [comment]
@upsuper  咦？我在书里有说「重复」吗 ？

**Comment by upsuper** [comment]
2.1.3 第二段第二句
> 核心库和标准库的功能有一些重复，也包括如下部分：

**Comment by ZhangHanDong** [comment]
@upsuper  OK，我再斟酌一下
