### ISSUE TITLE
「第五章」 `5.5.1` 节 代码清单5-29 代码错误

### ISSUE THREAD

**Issue by huoguangjin** [ZhangHanDong/tao-of-rust-codes#125]
# 页码与行数

- 第137页
- 代码清单 5-29 第4行

---

# 代码错误

[代码清单 5-29](https://github.com/ZhangHanDong/tao-of-rust-codes/blob/fccb2172311e37efdf7b0d434f703af5a302b6f6/src/ch05/lifetime.rs#L34)

```rust
s.push_str("Good ");
```
从后面的注释来看, 这里应该是:
```rust
s.push_str(" Good");
```

虽然代码清单 5-29是个编译不过的反例

**Comment by ZhangHanDong** [comment]
@huoguangjin 感谢反馈
