### ISSUE TITLE
「第十一章」thread::spawn 的栈默认大小为 2 MB 描述不准确

### ISSUE THREAD

**Issue by micooz** [ZhangHanDong/tao-of-rust-codes#126]
# 页码与行数

- 第372页，「定制线程」

---

# 文本或排版错误

> 直接使用 thread::spawn 生成的线程，默认没有名称，并且其栈大小默认为 2MB。

这里 2MB 描述并不准确，实际上应该是平台相关的，比如在 unix(l4re) 上是 1MB，在 wasm 上只有 4KB。

https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/libstd/sys_common/thread.rs#L24

https://github.com/rust-lang/rust/search?q=DEFAULT_MIN_STACK_SIZE&unscoped_q=DEFAULT_MIN_STACK_SIZE

**Comment by ZhangHanDong** [comment]
@micooz 感谢反馈。

 书旨在描述通用普遍的情况，事实上大部分平台默认都是2MB。当然是有特例存在的。

2MB的来源：[doc.rust-lang.org/stable/std/thread/index.html#stack-size](https://doc.rust-lang.org/stable/std/thread/index.html#stack-size)

不过我也可以在相关内容里再加一句关于特例的描述。
