### ISSUE TITLE
「第十一章」代码清单 11-22 最后批注有误

### ISSUE THREAD

**Issue by micooz** [ZhangHanDong/tao-of-rust-codes#127]
# 页码与行数

- 代码清单 11-22

---

# 文本或排版错误

> 所以代码第 16 行就可以对 data 数据进行打印直接输出 “recovered: 3”。

打印结果和代码不匹配，批注中的 3 应改为 2。

**Comment by ZhangHanDong** [comment]
@micooz 感谢反馈
