### ISSUE TITLE
「第五章」 `5.8` 节 关于GFC的疑问

### ISSUE THREAD

**Issue by huoguangjin** [ZhangHanDong/tao-of-rust-codes#130]
# 页码与行数

- 5.8节
- 第159页 中间位置

---

# 文本或排版错误

> - 借用检查第一阶段：计算作用域范围（Scope）内的借用。在GFC中的每个节点计算一系列的借用，并将其表示为元组，...

疑问：
这里出现了前后文未提及到的`GFC`，但在158页提到了`CFG`，猜测这里的`GFC`是否笔误？

**Comment by ZhangHanDong** [comment]
@huoguangjin 应该是笔误。Control Flow Graph的缩写是CFG。感谢反馈。
