### ISSUE TITLE
「第十二章」代码清单 12-52 断言测试用例错误

### ISSUE THREAD

**Issue by micooz** [ZhangHanDong/tao-of-rust-codes#131]
# 页码与行数

- 代码清单 12-52 第 8 行

---

# 代码错误

```rust
#![feature(proc_macro_hygiene)]

#[test]
fn test_hashmap() {
    let hm = hashmap!{ "a": 1, "b": 2 };
    assert_eq!(hm["a"], 1);
    let hm = hashmap!{ "a" => 1, "b" => 2, "c" => 3 };
    assert_eq!(hm["d"], 4); // 此处断言不通过
}
```

### Rust版本

```
$ rustc -V
rustc 1.34.0-nightly (d17318011 2019-02-07)
```

### 错误信息

```
thread 'test_hashmap' panicked at 'no entry found for key', src/libcore/option.rs:1038:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ZhangHanDong** [comment]
@micooz 感谢反馈，我再确认下。 应该是可以通过的。需要加#![feature(proc_macro_non_items)]。我知道你的编译环境是什么？加那个feature了吗？用Nightly了吗？报的错误是什么呢？

**Comment by micooz** [comment]
@ZhangHanDong 

已补充版本和错误信息。**proc_macro_*** 系列特性已经被合并为 **proc_macro_hygiene**，因此我测试时用的是后者，但我认为是断言本身就写错了，和这个特性无关。

PR: https://github.com/rust-lang/rust/pull/52121

**Comment by ZhangHanDong** [comment]
@micooz 那个错误的断言应该是故意为之，可能书上没写明确，就是想让大家看一下编译器对这种情况的错误信息。我再完善一下，感谢反馈。

**Comment by ZhangHanDong** [comment]
**proc_macro_*** 系列特性已经被合并为 **proc_macro_hygiene**
