### ISSUE TITLE
代码清单6-37 以及184页闭包规则总结问题

### ISSUE THREAD

**Issue by Observer42** [ZhangHanDong/tao-of-rust-codes#132]
# 页码与行数

- 第184页
- 规则总结 （使用move关键词。。。）
- 第182页
- 倒数两行
---

不加move关键词，仍然可以捕获值而非引用，只是优先度是 `&a > &mut a > a`
闭包自动实现Copy/Clone无关move关键词，只看capture的是否都是复制语义类型

## 例子

```rust
#[derive(Copy, Clone)]
struct Example(i32);

fn take<T: Copy>(_t: T) {}

fn main() {
    let a = 3;
    let c = || drop(a);
    take(c);
    c();
    c();

    let c2 = || println!("{}", a);
    c2();
    //take(c2);
    //error[E0277]: the trait bound `&mut i32: std::marker::Copy` is not satisfied in `[closure@src/main.rs:9:14: 9:23 a:&mut i32]`

    let e = Example(3);
    let another_closure = || drop(e);
    take(another_closure);
    another_closure();
    another_closure();
}

```
playground
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a5afa4b70238618531991d85327bab57

**Comment by ZhangHanDong** [comment]
@Observer42 感谢反馈，我再斟酌一下

**Comment by ZhangHanDong** [comment]
@Observer42  今天抽空看了下此问题，是这样的：

你说的是对的。但是和我书里讲的内容是两码事。也可能我书里没讲清楚，现在对内容做了如下的修改：

>  通过代码清单6-37看得出来，FnMut的闭包，在使用move关键字的时候，如果捕获变量是复制语义类型的，则闭包会自动实现Copy/Clone；如果捕获变量是移动语义类型的，则闭包不会自动实现Copy/Clone，这也是出于保证内存安全的考虑。

这里修改的地方主要是「FnMut的闭包」。结合代码清单6-37再理解一下。FnMut的闭包在使用move的情况下，会自动实现Copy。而没有move的情况下，不会自动实现Copy。

**Comment by ZhangHanDong** [comment]
@Observer42  今天抽空看了下此问题，是这样的：

你说的是对的。但是和我书里讲的内容是两码事。也可能我书里没讲清楚，现在对内容做了如下的修改：

>  通过代码清单6-37看得出来，FnMut的闭包，在使用move关键字的时候，如果捕获变量是复制语义类型的，则闭包会自动实现Copy/Clone；如果捕获变量是移动语义类型的，则闭包不会自动实现Copy/Clone，这也是出于保证内存安全的考虑。

这里修改的地方主要是「FnMut的闭包」。结合代码清单6-37再理解一下。FnMut的闭包在使用move的情况下，会自动实现Copy。而没有move的情况下，不会自动实现Copy。

**Comment by Observer42** [comment]
@ZhangHanDong 你好，我感觉还是有些问题

```rust
fn take<F: Copy + FnMut() -> ()>(_f: F) {}
fn call<F: Copy + FnMut() -> ()>(mut f: F) {
    f();
}

fn main() {
    let a = Some(3);
    let c = || {
        let a = a.unwrap();
        println!("{}", a);
    };
    take(c);
    call(c);
}
```
如上，c是FnMut的闭包，然而在没有使用move关键字时，因为捕获的变量是Copy的，c仍然自动实现了Copy

6-37这个例子是想回答你提出的问题： `move关键字是否只影响捕获自由变量的所有权的转移情况，而不影响闭包本身呢？`

我的理解是：

1. `move关键字影响了捕获自由变量的所有权的转移情况`，即move强制以复制/移动的方式捕获变量

2. `move不直接影响闭包本身`
6-37举的例子说明了如果闭包捕获的变量都是复制语义的，那么这个闭包会实现Copy/Clone。
上面贴的例子同样说明了这一点，但区别是没有使用move关键词

> 这里修改的地方主要是「FnMut的闭包」。结合代码清单6-37再理解一下。FnMut的闭包在使用move的情况下，会自动实现Copy。而没有move的情况下，不会自动实现Copy。

这样这句话就不成立了

> 通过代码清单6-37看得出来，FnMut的闭包，在使用move关键字的时候，如果捕获变量是复制语义类型的，则闭包会自动实现Copy/Clone；如果捕获变量是移动语义类型的，则闭包不会自动实现Copy/Clone，这也是出于保证内存安全的考虑。

我们可以看到，去掉 `在使用move关键字的时候` 这段，这句话还是成立的

回到
`move关键字是否只影响捕获自由变量的所有权的转移情况，而不影响闭包本身呢？`
你这里的回答是 `否`。
我的判断是，move的确影响了闭包本身，但这种影响是间接的（通过改变捕获变量的方式），而且并不是只有move会产生这种影响

或者说我的表述是
1. `move关键字改变了捕获自由变量的所有权的转移情况`
2. `捕获变量的类型决定了闭包是否实现Copy/Clone`

**Comment by ZhangHanDong** [comment]
@Observer42 

你这个例子和我书里的示例是不一样的。你这个会生成Fn trait的闭包

```rust

fn take<F: Copy + Fn() -> ()>(_f: F) {}
fn call<F: Copy + Fn() -> ()>(mut f: F) {
    f();
}

fn main() {
    let a = Some(3);
    let c = || {
        let a = a.unwrap();
        println!("{}", a);
    };
    take(c);
    call(c);
}
```

我书的例子，只会生成FnMut，不会生成Fn。
