### ISSUE TITLE
「第二章」`2.3.3 所有权和引用` 建议直接将“引用”表述为“借用”

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#133]
# 页码与行数

- 第 16 页
- 第 17 页
- 2.3.3 小节

---

# 文本或排版错误

虽然本小节最后提到

> 所以引用也被称为借用

但 Rust 中似乎已经有了 `ref` 关键字，这一 *小节* 把 `borrow` 这个概念翻译为 `引用` ，是否会引起误会？  

---

> Rust 提供**引用操作符（&）**，可以直接获取表达式的存储单元地址，即内存位置

[官方文档]中的描述方案正好和书里的相反，写的是 
> BorrowExpression ... this expressions produces a reference (pointer) to the location that the value refers to.

对于 `&` 符号，文档里写的也是 `borrow operators`，这里翻译成 `借用操作符（&）` 是不是会更加准确一些？

建议将这里改为

Rust 提供**借用操作符（&）**，本质上是对内存地址的 *引用*，可直接获取表达式 的存储单元地址，即内存位置。

---

btw, 新年快乐！

[官方文档]: https://doc.rust-lang.org/reference/expressions/operator-expr.html#borrow-operators

**Comment by ZhangHanDong** [comment]
@eZioPan 同乐同乐，感谢反馈！我斟酌一下

**Comment by eZioPan** [comment]
@ZhangHanDong 

我刚才翻了翻文档，发现新发现了一些东西

若 `&` 作为 `操作符`，出现在 **值表达式上下文** 中，就被称为 `borrow operator`  

若 `&` 作为 `类型标记`，出现在 **位置表达式上下文** 中，就被称为 `reference`

Rust Reference:
[Pointer types](https://doc.rust-lang.org/reference/types/pointer.html)  
[Borrow Operators](https://doc.rust-lang.org/reference/expressions/operator-expr.html#borrow-operators)

---

这样说来，到也是符合英文的描述习惯

`reference` 是 **名词**，强调 *结果* 和 *状态*

`borrow` 是 **动词**，强调 *行为* 和 *动作*

`borrowing` 是 **名词**，用来客观表述 borrow *这个动作本身*

Rust Book:
[References & Borrowing](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html)

**Comment by ZhangHanDong** [comment]
@eZioPan 很好的建议。

**Comment by eZioPan** [comment]
@ZhangHanDong 17 页还有一些地方需要一并修改了，不要忘了噢
