### ISSUE TITLE
Kindle 版本代码块割裂

### ISSUE THREAD

**Issue by hackerer1c** [ZhangHanDong/tao-of-rust-codes#139]
<img width="682" alt="2019-02-22 9 51 45" src="https://user-images.githubusercontent.com/18899791/53246577-1096a280-36ec-11e9-897b-b3f8fceaed8f.png">

应该是纸质版本分页导致的。

**Comment by ZhangHanDong** [comment]
@hackerer1c 感谢反馈。 这个和纸版的排版没啥关系。编辑是专门做了数字排版。这个是kindle转码的问题，已经提交给了编辑。后续版本应该可以修复吧。
