### ISSUE TITLE
「第二章」代码清单2-5 打印变量排版错误

### ISSUE THREAD

**Issue by ZhangHanDong** [ZhangHanDong/tao-of-rust-codes#14]
# 页码与行数

- 第16页

---

# 代码错误

- 代码清单2-5，最后一行的other打印排版错误，应该打印place2

from: 过客whhema

**Comment by hetianpeng** [comment]
不止最后一行。
![img_4272](https://user-images.githubusercontent.com/5644311/50736209-89ea3c80-11f5-11e9-9cb3-d649a1313bc2.jpg)

**Comment by ariesdevil** [comment]
不光是最后一行，代码清淡 2-5 第 5 行也是错误，应该为 place1，另外下面的描述中也使用了 other，也是错误的

**Comment by ZhangHanDong** [comment]
@ariesdevil 感谢反馈。放到第三次印刷来修改此问题。
