### ISSUE TITLE
[第五章] 5.5.1节 图5-7 左右地址顺序相反

### ISSUE THREAD

**Issue by bistack** [ZhangHanDong/tao-of-rust-codes#144]
# 页码与行数

- 第142页

---

# 文本或排版错误

> 图5-7 排版，左侧 “代码段”，“数据段”顺序应匹配右侧的“数据区”和”代码区”，名称建议一样。
---

**Comment by ZhangHanDong** [comment]
@bistack 感谢反馈，回头我确认一下
