### ISSUE TITLE
[第二章]2.5.2中while_true表述会引起误解

### ISSUE THREAD

**Issue by Chris940406** [ZhangHanDong/tao-of-rust-codes#145]
# 页码与行数

- 第24页
- 第12行

---

# 文本或排版错误

> ...程序在运行以后，将永远在while true循环中执行。

由于return的存在，会直接返回，这里可能会引起误解，建议删除或者改为在没有return的情况下，会永远在循环中执行。

**Comment by ZhangHanDong** [comment]
@Chris940406 感谢反馈。不过，这个问题已经有人提过了，重复了。
