### ISSUE TITLE
「第四章」4.1.1 的配图 4-4 左侧栈方向上下反了

### ISSUE THREAD

**Issue by Rivsen** [ZhangHanDong/tao-of-rust-codes#148]
# 页码与行数

- 第98页

---

# 文本或排版错误

> 图 4-4中的左侧栈方向和右侧的 EBP ESP 方向不对，按照右侧和图 4-5 的栈方向，这个图中的栈开口应该朝下

**Comment by ZhangHanDong** [comment]
@Rivsen  感谢反馈

**Comment by dwing4g** [comment]
其实大多数人更习惯栈顶在上,也就是右图反了, 地址从低到高改为从上到下就好了.

**Comment by ZhangHanDong** [comment]
@dwing4g  就这样吧，改左图方便
