### ISSUE TITLE
「第二章」`2.4.5 CTFE机制` trait拼写错误

### ISSUE THREAD

**Issue by zc58778560** [ZhangHanDong/tao-of-rust-codes#149]
# 页码与行数

- 第20页
- 2.4.5 CTFE机制，最后第二段，第2行

---

# 文本或排版错误
> 可以为所有长度的数组实现 triat Foo。

triat 应改为 trait

**Comment by ZhangHanDong** [comment]
@zc58778560 感谢反馈
