### ISSUE TITLE
[电子版][第二章] 2.6.9 never 类型：拼写错误

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#151]
# 页码与行数

- 2.6.9 never 类型
- 代码清单 2-32：neüer 类型示例

---

# 文本或排版错误

> neüer 类型示例

应为 `never 类型示例`

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈，这个估计是转码的问题

**Comment by xiaods** [comment]
纸质版本没有这个问题。

**Comment by ZhangHanDong** [comment]
嗯
