### ISSUE TITLE
[第六章] ‘6.2.3 闭包与所有权’ 对于闭包capture移动语义变量实现机制的质疑

### ISSUE THREAD

**Issue by Suida** [ZhangHanDong/tao-of-rust-codes#152]
# 180页
该书180页加粗小标题 “移动语义类型自动实现 `FnOnce`” 及其统属模块内容有误：
在 rust 版本:
```bash
# rustc -V
rustc 1.32.0 (9fda7c223 2019-01-16)
```
下，只有当闭包捕获了移动语义类型**并且使用了移动语义**才会只为闭包实现 trait `FnOnce`，如果没有使用环境变量的移动语义则会默认实现 trait `Fn`。机制如下代码所示：
```rust
use std::fmt::Display;

fn borrow<T: Display>(t: &T) {
    println!("Borrowed: {}", t);
}

fn own<T: Display>(t: T) {
    println!("Owned: {}", t);
}

fn is_Fn<F: Fn()>(f: F) {
    f();
}

fn main() {
    let s = String::from("hello");
    let c = || borrow(&s);
    is_Fn(c);

    let s = String::from("hello");
    let c = || own(s);
         // ^^^^^^^-^
         // |      |
         // |      closure is `FnOnce` because it moves the variable `s` out of its environment
         // this closure implements `FnOnce`, not `Fn`
    // is_Fn(c);
    // ----- the requirement to implement `Fn` derives from here
}
```

如果没有倒数第三行的 `is_Fn(c);` 代码将通过编译，而加上后将会出现所注释的错误。因此可以推测，如果在闭包中如果不移动 “移动语义环境变量” 的所有权，rust 仍然会为这个闭包实现 `Fn` 而不是 `FnOnce`。

*最后*，感谢作者的努力工作能让我更好的学习 rust 语言，如质疑有误还望海涵。

**Comment by ZhangHanDong** [comment]
@Suida 感谢你的反馈。

然而，我180页那个示例，旨在说明 「移动语义的变量被自动捕获」情况下，是默认实现FnOnce。你这个例子里，已经是使用了借用（&s），当然会实现Fn。

我书里的内容，是把知识点拆解开零散的点来讲解，不要把其他的情况（按引用捕获）来质疑（移动语义自动捕获）当前的这种情况。
