### ISSUE TITLE
「第五章」 `5.5.1` 节 代码清单5-35 5-36 代码错误

### ISSUE THREAD

**Issue by wucheng** [ZhangHanDong/tao-of-rust-codes#154]
# 页码与行数

- 第141页

---

也不严格的说是错误的，但是expect里面写could not find a ,。 会更人的误解是next如果返回的none，那么表明没有逗号。

对于不包含逗号的字符串，split后，调用第一次next返回的都是本身。所以如果要通过split来判断是否有逗号，就要调用next两次

**Comment by ZhangHanDong** [comment]
@wucheng 感谢反馈。 代码示例只是为了解释当前的知识点，你可以发挥你的思考去修改它，进一步改善它。但你不能说它是错误的，除非编译出现了问题。
