### ISSUE TITLE
[第三章] 88页倒数第二行，表意不精确

### ISSUE THREAD

**Issue by current1990** [ZhangHanDong/tao-of-rust-codes#158]
88页，倒数第二行

> 使用了<T: Into<String>>限定就意味着，实现了into方法的类型都可以作为参数。

应该说是

> 使用了<T: Into<String>>限定就意味着，实现了Into<String>这个trait的类型都可以作为参数。

**Comment by ZhangHanDong** [comment]
@current1990 感谢反馈。不过这里描述并没有问题。  我说的是Into这个trait里的into方法，不是trait。当然，你理解为实现Into trait也是没有问题的。 实现trait，就是实现里面的方法，道理一样。
