### ISSUE TITLE
「第二章」2.1.3 核心库 的一些问题

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#159]
# 页码与行数

- 第12页
- 2.1.3 核心库

---

# 文本或排版错误

这里面问题比较多。 #124 提到了一些。

我在 #124 的comment里面也提到了，std基本上re-export了core定义的东西，而std和core在使用上基本是互斥的，所以这并不是什么重复。

另外基本上所有涉及到allocation的容器和智能指针（包括你在里面列的“常用功能型数据类型”中所有的类型）全都是不可能出现在core的。这些基本上会出现在alloc或者只是std里。core意味着不能有任何外部库依赖，也就不可能有调用allocation的东西存在。

**Comment by upsuper** [comment]
相反的，像后面2.1.4标准库一节里提到的“底层操作接口”实际上全都是在core里定义然后re-export进std的，`Option`和`Result`也是。

**Comment by ZhangHanDong** [comment]
@upsuper 对，这个已经勘误了。第二章开头写的太早，后续没有专门针对这一小节review问题，是个失误。

**Comment by ZhangHanDong** [comment]
再一次修正了一些描述。

> 重用（re-export）了核心库一些基本trait、原始数据类型、功能型数据类型和常用宏等，所以会看到一些与核心库几乎完全一致的API。
