### ISSUE TITLE
「第二章」2.4.3 函数指针中关于函数为一等公民的说法

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#160]
# 页码与行数

- 第19页
- 2.4.3 函数指针

---

# 文本或排版错误

> 在Rust中，函数为一等公民。

在Rust中函数是不是一等公民姑且不论，函数指针与一等公民函数之间没有一点关系。在C里也有函数指针，也可以作为参数和返回值，但从来没有人会声称在C里函数是一等公民。

函数的一等公民通常是用来指可以在运行时构建函数，亦即通常是指closure。一等公民这种提法不适合放在函数指针这节。

**Comment by ZhangHanDong** [comment]
@upsuper  感谢反馈。我会再斟酌。

**Comment by ZhangHanDong** [comment]
修订为：

> 在Rust中，函数为一等公民（first-class function）。这意味着，函数自身就可以作为函数的参数和返回值使用。在Rust里，函数作为参数或返回值进行传递的时候，是通过函数指针类型或闭包来实现的。
