### ISSUE TITLE
「第二章」代码清单2-19 的修改方法不符合常见做法

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#161]
# 页码与行数

- 第24页
- 代码清单2-19

---

# 代码错误

```rust
fn while_true(x: i32) -> i32 {
    while true {
        return x+1;
    }
    x // 此处通常使用 unreachable!()
}
```

在实际使用过程中，完全有循环理论上总会在结束之前`return`，但因为不是`loop`而无法满足类型推断的情况出现，在这种情况通常的做法是使用`unreachable!()`而不是随意使用一个值来敷衍类型检查。

此处代码的做法不符合实践中的做法，建议修改。

**Comment by ZhangHanDong** [comment]
@upsuper 感谢反馈。

这里具体的示例主要是想说明`while true`的问题，并且引出后续CTFE的说明，是想说明概念。不过对于你的补充，我会考虑在后续加上说明。

**Comment by flycrane** [comment]
书上解释说 “程序在运行以后，将永远在while true循环中执行”， 但是return 会导致函数返回的吧，怎么能循环下去的呢？

**Comment by ZhangHanDong** [comment]
@flycrane  这可能是文字描述有歧义引起你的误会。这里有个勘误：https://github.com/ZhangHanDong/tao-of-rust-codes/issues/145 看看这个吧
