### ISSUE TITLE
「序」关于写下代码几天后无法编译的情况建议进行说明

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#163]
# 页码与行数

- 第VIII页
- “为什么要写这本书”下第二段第二行

---

# 文本或排版错误

> 举一个极端的例子，……

这个例子虽然可以体现出Rust的快速成长，但与Rust 1.0以后对稳定的坚持有所冲突。理论上说一个代码只要不使用只在Nightly里能用的unstable特性，就不应该出现写出来能编译过过一段就过不了的情况。所以这里建议加一个脚注对此进行说明，不然不了解情况的人可能会将其理解为一个Rust频繁进行breaking change，依然不适合用在生产环境的信号。

**Comment by ZhangHanDong** [comment]
@upsuper 感谢反馈。不过我说的是实情，比如内存分配相关API的变化。不过你说的确实是个问题，我会考虑修改一下。

**Comment by ZhangHanDong** [comment]
加了一个脚注：

「注意：因为成书比较早，有些示例也使用了开发版（Nightly） Rust的一些API，当时还未稳定发布，所以会遇到一些API变更的情况。并非是指稳定版（Stable） Rust。稳定版Rust不会出现这种情况。」
