### ISSUE TITLE
「第二章」if语句的条件不需要括号

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#166]
# 页码与行数

- 第22页
- 代码清单2-16

- 第34页
- 代码清单2-34

---

# 代码错误

数处代码中的`if`语句的条件包上了括号，这是不需要的，而且可能给新手带来困惑。因为很多语言的`if`语句强制要求条件要带括号，所以这里或许更应该额外说明括号是不需要的。

**Comment by ZhangHanDong** [comment]
@upsuper  感谢反馈。 不过我的看法是，这些细节留给读者自己去思考吧，反正他们也是需要动手的，编译器会提示他们的。

**Comment by islishude** [comment]
刚遇到这个问题，提示

warning: unnecessary parentheses around `if` condition
  --> src/main.rs:34:25
   |
34 |         let gender = if (self.gender == 1) { "boy" } else { "girl" };
   |                         ^^^^^^^^^^^^^^^^^^ help: remove these parentheses
   |
   = note: #[warn(unused_parens)] on by default

需要去掉括号，这真的很让人困惑。。

**Comment by ZhangHanDong** [comment]
@islishude 这个只是编译器给你的警告，友情建议，按提示去掉多余的括号就可以了
