### ISSUE TITLE
「第二章」“这样的枚举值本质上属于函数指针类型”这种表述有问题

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#167]
# 页码与行数

- 第37页
- 代码清单2-41下一行

---

# 文本或排版错误

> 这样的枚举值本质上属于函数指针类型。

从这里基本上我觉得你对Rust里的函数与函数指针的认识有根本上的问题。

你可以说枚举值可以被作为函数使用，但函数在类型上与函数指针是完全不一样的，这个之前群里正好有讨论过。每个函数自身（包括每个闭包）都是一个*独立*的类型，其中使用fn声明的函数和不捕获环境中变量的闭包是零大小类型（即ZST），而所有签名相同的ZST函数可以coerce到该签名的函数指针，指向这个函数的地址。函数指针的大小是固定的，是跟函数不同的类型。

**Comment by ZhangHanDong** [comment]
@upsuper 感谢反馈。反馈前可以翻一下勘误，这个已经勘误过了。 

见:

- [issues/42](https://github.com/ZhangHanDong/tao-of-rust-codes/issues/42)
- [《Rust编程之道》读者答疑精选：函数项类型和函数指针类型](https://zhuanlan.zhihu.com/p/54485063)

**Comment by upsuper** [comment]
我搜第二章没搜到……

**Comment by ZhangHanDong** [comment]
@upsuper issues有label标签：「第二章」，还有「精选」也推荐看一下，是比较重要的勘误。
