### ISSUE TITLE
「第二章」BTreeMap不是哈希表……

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#169]
# 页码与行数

- 第38页
- 2.8 常用集合类型下第三行

---

# 文本或排版错误

> Key-Value映射表：无序哈希表（HashMap）、有序哈希表（BTreeMap）

首先……哈希表一般认知中就是无序的，在我所知的范围内不存在所谓的“有序哈希表”一说，即使存在，也不是这里的BTreeMap。

B-tree是一类平衡树结构，与哈希表在构造上是本质不同的。建议阅读相关数据结构的介绍。

**Comment by ZhangHanDong** [comment]
@upsuper  感谢反馈。这里是说的不严谨，我本意是可以把它当作一个「有序的哈希表」去使用。这里的说明需要修改。

**Comment by upsuper** [comment]
你可以说它是有序的映射表……哈希表一般是特指使用哈希的方法来做映射的表，这两种映射的实现方式对各种操作有不同的时间复杂度

**Comment by ZhangHanDong** [comment]
@upsuper 嗯，收到。

**Comment by ZhangHanDong** [comment]
修订为： 有序映射表（BTreeMap）
