### ISSUE TITLE
「第二章」2.8.1 向量中说“编译器会报panic错误”

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#170]
# 页码与行数

- 第39页
- 2.8.2标题的上一行

---

# 文本或排版错误

> 调用v3[4]，编译器会报panic错误：

编译器不会报这个错，这个错误是运行时的。

**Comment by ZhangHanDong** [comment]
@upsuper 感谢反馈。 这是个失误。
