### ISSUE TITLE
［问题］如何从返回值为`impl Future`的函数中提前返回？

### ISSUE THREAD

**Issue by GopherJ** [ZhangHanDong/tao-of-rust-codes#172]
您好，抱歉开了一个与本书无关的issue，一个使用中遇到的问题，想请教一下您．

rust 中 if 和 else 两个 block 的返回值必须相同，我遇到的情况是在使用 actix-web 框架中，某些路由需要提前返回一个HttpResponse，而不需要发送信息给 database actor，想问一下您这种情况如何处理可以做到提前返回呢？

以下是代码和报错的截图：
![Screenshot from 2019-03-11 12-02-14](https://user-images.githubusercontent.com/33961674/54180528-2d78f700-449c-11e9-80df-f07711f2e154.png)

![Screenshot from 2019-03-11 12-07-08](https://user-images.githubusercontent.com/33961674/54180541-3073e780-449c-11e9-8dec-9276976b3c31.png)

**Comment by ZhangHanDong** [comment]
@GopherJ  这里最好问和书相关的问题。

你返回的类型不对，注意看编译器提示。你不能返回and_then类型，actix需要的是future对象，你需要使用.into_future()来转成future对象。

**Comment by GopherJ** [comment]
@ZhangHanDong 您好，错误并非来自AndThen,这个类型本身就实现了Future特征无需再转，错误是if的每个分支要求返回同样的类型，哪怕这些类型都impl了同一个trait并且函数值返回值就是impl 某个trait，只要每个分支类型不同就不行．

我也没有找到将AndThen转换为其他类型和将一个单纯的类型转换为AndThen的方法

**Comment by GopherJ** [comment]
@ZhangHanDong 您好，AndThen并未实现IntoFuture

**Comment by GopherJ** [comment]
用box打包可以
![Screenshot from 2019-03-13 12-04-28](https://user-images.githubusercontent.com/33961674/54274445-68585900-4588-11e9-923b-6a0af2d174e8.png)
