### ISSUE TITLE
「第一章」增加关于如何启用 Rust 2018 版本的说明

### ISSUE THREAD

**Issue by AmaiKinono** [ZhangHanDong/tao-of-rust-codes#173]
# 页码与行数

- 第 8 页
- 第 6 行

---

# 建议

首先是这里讲到的「开发者选择 "edition=2018"」，显得不清不楚。具体来说是在 `cargo.toml` 的 `[package]` 字段中加入 `edition=2018`，似乎这也是 cargo 的默认行为了，希望可以写清楚这一点。

另外就是有时候我们做一些小实验，可能会直接用单个文件写代码然后编译，而不借助 cargo，这时候可以使用 rustc 的 `--edition 2018` 参数，希望把这种方式也加进去。

**Comment by ZhangHanDong** [comment]
@AmaiKinono  感谢反馈。这只是第一章，不要着急，我写书组织内容是假设读者能看完一本书的，内容是逐渐推进的。

而且，在本书出版的时候，Rust 2018就stable了。如果用1.31以上的版本，就没必要加这个参数了。不过你这个建议我可以加到附录A里。

**Comment by AmaiKinono** [comment]
@ZhangHanDong 嗯我理解了。不过
> 如果用1.31以上的版本，就没必要加这个参数了。
「这个参数」是指 `--version 2018` 吗？我这里 rustc 的版本是
```
$ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```
似乎还是必须加上这个参数的。我试了这个例子：
``` rust
fn main() {
    let mut x = 5;
    let y = &x;
    let z = &mut x;
}
```
不加 `--version 2018` 编译会报 error，加了以后可以通过。可见 rustc 1.33 要想启用 2018 版本还是要加这个参数的。

**Comment by ZhangHanDong** [comment]
@AmaiKinono 噢？还有这种事。感谢反馈。

**Comment by ZhangHanDong** [comment]
@AmaiKinono 已修改。感谢反馈。
