### ISSUE TITLE
「第三章」3.1.2 类型系统的分类中关于自动推导的叙述有问题

### ISSUE THREAD

**Issue by upsuper** [ZhangHanDong/tao-of-rust-codes#174]
# 页码与行数

- 第52页
- 3.1.2下第二段倒数第二行

---

# 文本或排版错误

> Rust语言的类型系统受Haskell启发，也可以自动推导，但不如Haskell强大。在Rust中大部分地方还是需要显式地指定类型的，……

Rust在变量类型上大部分地方都可以自动推导，并不存在大部分地方需要显式指定的情况。然而Rust要求函数参数及返回值需要显式指定类型是因为Rust将函数签名看做一个契约，作为对函数部分行为的一个形式化描述。这各部分要求指定并不是因为Rust不够强大无法推导。

**Comment by upsuper** [comment]
后面第60页“类型推导的不足”里说
> 用Rust变成的时候，应尽量显式声明类型，……

首先据我所知并没有这种说法，基本上只需要当编译器明确告诉你需要显式声明的时候声明即可。

其次整数的类型并不需要透过类型声明来给出，更常见的做法是通过类型后缀如 `0u32` 这样的形式。

**Comment by ZhangHanDong** [comment]
@upsuper  感谢反馈。

这个「大部分」应该是写的时候想当然了。不过，我也并不是指「函数参数指定类型」不能推导。
「尽量显式声明」那句确实有问题，我现在好奇自己当时是怎么写出这个结论 。。。

**Comment by ZhangHanDong** [comment]
修订

> 「大部分」改为「有些」
>  在用Rust编程的时候，需要看情况，有时候显式声明类型可以避免一些麻烦。
