### ISSUE TITLE
「第四章」4.1.1 foo函数不会将x压栈

### ISSUE THREAD

**Issue by netcan** [ZhangHanDong/tao-of-rust-codes#175]
# 页码与行数
- 99页
# 文本或排版错误
main函数会将参数x压栈，然后是返回地址，接着是旧的ebp，进入到foo栈帧中，而foo不会把参数x压栈，只会通过ebp+8来取x，也就是说，foo只压入y和z。

**Comment by ZhangHanDong** [comment]
@netcan 感谢反馈，我抽空确认一下。

**Comment by kvinwang** [comment]
函数参数是会压栈的，没有问题。
foo里面不可能知道上层栈帧中x的地址，除非被inline优化。

**Comment by netcan** [comment]
> 函数参数是会压栈的，没有问题。
> foo里面不可能知道上层栈帧中x的地址，除非被inline优化。
> 不好意思，看错了，以为说x不会压栈。
> 
> 不过
> 
> > 只会通过ebp+8来取x
> 
> 应该是 ESP+8（按书上的ABI约定的话）

是的，foo会通过ebp+8来取x，不需要压栈x。
```
void foo(int x) {
	int y = x;
	int z = 100;
}

int main() {
	int x = 42;
	foo(x);
}
```
汇编代码如下：
```

t.o:     file format elf32-i386


Disassembly of section .text:

00000000 <foo>:
   0:	55                   	push   %ebp
   1:	89 e5                	mov    %esp,%ebp
   3:	83 ec 10             	sub    $0x10,%esp        ; 分配栈帧大小
   6:	8b 45 08             	mov    0x8(%ebp),%eax    ; 取x(ebp + 8)
   9:	89 45 fc             	mov    %eax,-0x4(%ebp)   ; 存到y中
   c:	c7 45 f8 64 00 00 00 	movl   $0x64,-0x8(%ebp)  ; z = 100
  13:	90                   	nop
  14:	c9                   	leave  
  15:	c3                   	ret    

00000016 <main>:
  16:	55                   	push   %ebp
  17:	89 e5                	mov    %esp,%ebp
  19:	83 ec 10             	sub    $0x10,%esp         ; 分配栈帧大小
  1c:	c7 45 fc 2a 00 00 00 	movl   $0x2a,-0x4(%ebp)   ; x = 45
  23:	ff 75 fc             	pushl  -0x4(%ebp)         ; main压入x，即传参
  26:	e8 fc ff ff ff       	call   27 <main+0x11>     ; call foo
  2b:	83 c4 04             	add    $0x4,%esp
  2e:	b8 00 00 00 00       	mov    $0x0,%eax
  33:	c9                   	leave  
  34:	c3                   	ret    

```

**Comment by kvinwang** [comment]
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0bcbbac8bb1e75ffe07b9e1b194add98)里面编译看了，书上没错, x会压栈，并且是在foo里面压栈的
```
playground::foo:
	subq	$12, %rsp
	movl	%edi, (%rsp); 这里压栈x参数
	movl	(%rsp), %edi
	movl	%edi, 4(%rsp)
	movl	$100, 8(%rsp)
	addq	$12, %rsp
	retq

playground::main:
	pushq	%rax
	movl	$42, 4(%rsp)
	movl	4(%rsp), %edi
	callq	playground::foo
	popq	%rax
	retq
```

**Comment by netcan** [comment]
> [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0bcbbac8bb1e75ffe07b9e1b194add98)里面编译看了，书上没错, x会压栈，并且是在foo里面压栈的
> 
> ```
> playground::foo:
> 	subq	$12, %rsp
> 	movl	%edi, (%rsp); 这里压栈x参数
> 	movl	(%rsp), %edi
> 	movl	%edi, 4(%rsp)
> 	movl	$100, 8(%rsp)
> 	addq	$12, %rsp
> 	retq
> 
> playground::main:
> 	pushq	%rax
> 	movl	$42, 4(%rsp)
> 	movl	4(%rsp), %edi
> 	callq	playground::foo
> 	popq	%rax
> 	retq
> ```

你这是x64位的指令集了，在main中，通过将`x`存放到%edi寄存器中，然后在foo()函数压栈取出x，那么在main就不需要压栈x了

**Comment by kvinwang** [comment]
总的来说书上的说法没有问题。

利用寄存器是属于优化问题，这里讨论原理本身，不应虑这种优化。原理上，参数肯定需要压栈的，只有处于叶子上(没有调用其它函数)的函数可以优化掉压栈操作，rust debug下即使“叶子”函数也没有优化，老老实实地压栈。 

从`ebp + 8`取值应当也是优化问题，想象一下如果foo被两个地方调用，那么`ebp + 8`代表什么地址呢？

**Comment by netcan** [comment]
> 总的来说书上的说法没有问题。
> 
> 利用寄存器是属于优化问题，这里讨论原理本身，不应虑这种优化。原理上，参数肯定需要压栈的，处于叶子上(大概理解为没有调用其它带参函数)的函数可以优化掉压栈操作，rust debug下即使“叶子”函数也没有优化，老老实实地压栈。
> 
> 你的C代码编译结果中从`ebp + 8`取值应当也是优化问题，想象一下如果foo被两个地方调用，那么`ebp + 8`代表什么地址呢？

一般来说，调用者负责压栈传参，被调者通过ebp + offset来取参数，这是约定。比如写汇编程序，让C调用，那么自己编写的汇编程序的函数可以假定第一个参数为ebp+8，第二个参数为ebp+12，以此类推

**Comment by kvinwang** [comment]
>一般来说，调用者负责压栈传参，被调者通过ebp + offset来取参数，这是约定。比如写汇编程序，让C调用，那么自己编写的汇编程序的函数可以假定第一个参数为ebp+8，第二个参数为ebp+12，以此类推。

你这个说法需要一种call ABI约定为前提

**Comment by netcan** [comment]
> > 一般来说，调用者负责压栈传参，被调者通过ebp + offset来取参数，这是约定。比如写汇编程序，让C调用，那么自己编写的汇编程序的函数可以假定第一个参数为ebp+8，第二个参数为ebp+12，以此类推。
> 
> 你这个说法需要一种call ABI约定为前提。
> 书上讲的是Rust，当然以Rust的ABI约定(当前实现)来介绍。你以C的多种ABI约定中的一种来说，显然是不对的。

好吧，看了一下，目前Rust的ABI还没定义，讨论也很有意思- -
https://github.com/rust-lang/rfcs/issues/600

**Comment by ZhangHanDong** [comment]
@kvinwang @netcan 讨论很有意义。也许我需要在这个内容处稍加一些关于Rust ABI的说明。
