### ISSUE TITLE
「第四章」4.2.2 小节 使用Valgrind来检测内存泄漏

### ISSUE THREAD

**Issue by netcan** [ZhangHanDong/tao-of-rust-codes#177]
# 页码与行数
- 109页
# 文本或排版错误
Valgrind一般对系统默认的函数malloc/free等打补丁，进行内存使用跟踪，无法直接用在rust程序上的，参考这篇Blog：
https://creativcoder.github.io/post/checking_memory_leaks_in_rust_ffi/

The reason behind this is with the use of jemalloc being used as the default allocator in rustc, which as of now doesn’t play well with valgrind (See details on this issue)

But fear not, rust also allows us to fallback to os’s default allocator i.e., the free and malloc. This can be opted in by using compiler attributes at your crate root (lib.rs) as shown below. ( NOTE: Switching allocators only works for nightly release as of now. So just do a rustup override set nightly )
```
#![feature(alloc_system)]
extern crate alloc_system;
```

**Comment by ZhangHanDong** [comment]
@netcan 感谢反馈。 
不过你可能理解错了，这篇文章说的是Valgrind和jemalloc不太合，所以没有检测出内存泄漏，然后换了系统内存分配器就可以使用Valgrind检测出内存泄漏了。
而且这篇文章已经过时了，现在Rust最新版已经默认不使用Jemalloc了。

**Comment by netcan** [comment]
没，Valgrind默认只对malloc/free等有效，其他的检测不出来。

我用blog的内存泄漏代码测试，Valgrind也检测不出来。
```
use std::mem;

pub fn allocate() {
    use std::mem;
    let mut bad_vec: Vec<char> = Vec::with_capacity(1024);
    for _ in 0..1024 {
        bad_vec.push('0');
    }
    mem::forget(bad_vec);
}

fn main() {
    allocate();
}
```

**Comment by kvinwang** [comment]
rust现在默认就是调用libc的malloc分配内存

**Comment by ZhangHanDong** [comment]
@netcan   https://stackoverflow.com/questions/51509314/why-does-valgrind-not-detect-a-memory-leak-in-a-rust-program-using-nightly-1-29   

看博客的时候注意是不是过期了
