### ISSUE TITLE
[第五章] 5.5.1节 返回的借用生命周期必须比出借方的生命周期长

### ISSUE THREAD

**Issue by netcan** [ZhangHanDong/tao-of-rust-codes#178]
# 页码与行数

- 第140页

---

# 文本或排版错误
**返回的借用生命周期必须比出借方的生命周期长**，应该是返回的借用生命周期不长于出借方的生命周期

**Comment by ZhangHanDong** [comment]
@netcan 感谢反馈。这个勘误重复了。
