### ISSUE TITLE
「第二章」增补源码编码描述

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#18]
在 `2.6.3` 节 `字符类型` 中，可在介绍 Rust 的 `char` 类型的同时，也同时介绍 Rust 的源代码文件 `.rs` 文件的默认文本编码格式为 `utf-8` ，且不支持其他文本编码格式

**Comment by ZhangHanDong** [comment]
@mzji 感谢反馈。
不过你的建议还需要斟酌。第二章的内容组织，目的是让读者过一遍语法，这里讲Char的时候，可能不便插入其他内容。
其实在第8章专门讲字符串的时候，详细介绍了utf8相关内容。你的提议倒是适合放到第8章。

**Comment by ZhangHanDong** [comment]
@mzji 

在8.1.3节中新增

> 所以，在Rust中字符串是UTF-8编码序列。同时也需要知道，Rust 的源代码文件 .rs 文件的默认文本编码格式也是UTF-8 ，且不支持其他文本编码格式。
