### ISSUE TITLE
8.2.2节代码清单8-62有误

### ISSUE THREAD

**Issue by Rivsen** [ZhangHanDong/tao-of-rust-codes#183]
# 页码与行数

- 第289页
- 第12行

---

# 文本或排版错误

代码清单 8-62 中的 `GapThenFull` 是一个结构体，不是枚举体。

**Comment by ZhangHanDong** [comment]
@Rivsen 感谢反馈。

**Comment by ZhangHanDong** [comment]
已修订，顺便增加了新的说明：

> 注意，在Rust 1.36版中，HashMap<K, V>底层的罗宾汉算法被替换成了Google Swiss Table算法的Rust实现hashbrown。两个算法的区别在于，在处理删除的时候，前者使用的是回溯（backshifting），而后者使用的是“墓碑”（tombstones），顾名思义，就是为删除的元素留下一个空位，并且使用“墓碑”来标记已删除状态。并且hashbrown还可以针对SIMD进行优化。
