### ISSUE TITLE
「第三章」3.2 Rust类型系统概述

### ISSUE THREAD

**Issue by s3nt3** [ZhangHanDong/tao-of-rust-codes#186]
# 页码与行数

- 第53页
- 第26行

---

# 文本或排版错误

> Rust把作用域也纳入了类型系统，这就是第4章将要学到的生命周期标记

生命周期标记在书中第5章介绍，此处应该是笔误。

**Comment by ZhangHanDong** [comment]
@s3nt3 感谢反馈
