### ISSUE TITLE
[第四章] 4.2.2 文字错误

### ISSUE THREAD

**Issue by myqq0000** [ZhangHanDong/tao-of-rust-codes#189]
# 107页 **确定性析构**小节下第第2段第4行
- 而GC是由第三方**只**针……
- 应为指针

**Comment by ZhangHanDong** [comment]
@myqq0000 收到，感谢反馈。

**Comment by dwing4g** [comment]
> 而GC是由第三方只针对内存来同一回收垃圾的,
难道不应该这样断句么: 由 第三方 只 针对 内存

**Comment by ZhangHanDong** [comment]
@dwing4g  对的
