### ISSUE TITLE
「第三章」 `3.1.3` 节 `类型系统与多态性` 中的描述错误

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#19]
# 页码与行数

- 第53页
- 第19~21行

---

# 概念错误

第 `3.1.3` 节 `类型系统与多态性`

> 而 Rust 语言重并没有类似 Java 中的继承的概念，所以也不存在子类型多态。所以，Rust 中的类型系统目前只支持参数化多态和 Ad-hoc 多态，也就是，泛型和 trait 。

实际上 Rust 支持 Subtyping ，但仅限于 lifetime 带来的 Subtyping 这一种情况。基于 lifetime 的 Subtyping 直接影响了 Rust 的 Variant & Covariant 规则。

可参见：[Rust nomicon: Subtyping and Variance](https://doc.rust-lang.org/nomicon/subtyping.html)

**Comment by ZhangHanDong** [comment]
@mzji 

最终修改为：

> 所以也不存在「继承式」的子类型多态。严格来说，Rust中也有另外一种只存在于生命周期中的子类型多态，具体在第13章有专门介绍。
