### ISSUE TITLE
[第三章] 代码清单3-9 never_type删除不影响代码运行

### ISSUE THREAD

**Issue by huanyusun** [ZhangHanDong/tao-of-rust-codes#194]
# 页码与行数

- 第58页
- 第6行

# 代码错误

```rust
#![feature(never_type)]
fn foo() -> ! {
    // ...
    loop { println!("jh"); }
}
```
### Rust版本

```
$ rustc -V
rustc 1.34.0 (91856ed52 2019-04-10)
```

### 错误信息

```rust
#![feature(never_type)] 删除后不会影响代码运行，不确定是否现在可以不使用这个了
```

**Comment by ZhangHanDong** [comment]
@huanyusun 感谢反馈

**Comment by ZhangHanDong** [comment]
通过查看 ： [Unstable book](https://doc.rust-lang.org/unstable-book/language-features/never-type.html)，发现并未稳定。

根据我测试的情况看，返回类型是`!`的应该是可以用了。stable下也可以。但是要作为指定类型，比如： 

```rust
let x: ! = {
    return 123
};
```

就需要` #![feature(never_type)]`了。
