### ISSUE TITLE
第二章，2.3.3 代码示例与描述不符合

### ISSUE THREAD

**Issue by islishude** [ZhangHanDong/tao-of-rust-codes#196]
# 页码与行数

kindle 版本看不到第几页。

第二章，2.3.3 代码清单 2-5

<img width="611" alt="屏幕快照 2019-04-18 下午5 38 06" src="https://user-images.githubusercontent.com/24730006/56351929-c409a800-6200-11e9-9912-d98f47e72130.png">

---

# 文本或排版错误

这里说 第 7 行代码会报错，但是实际上这段代码是正确的。

按照书上的内容，第7行内容应该是这样的

```rust
println!("{:?}", place2); // 这样第7行就是错的
```

---

# 代码错误

-

### Rust版本

```
$ rustc -V
rustc 1.32.0-nightly (8b096314a 2018-11-02)
```

### 错误信息

```rust
error: xxxx
xxxx
xxxx
```

**Comment by islishude** [comment]
另外问下，kindle 版本会不会跟着更新内容？

**Comment by ZhangHanDong** [comment]
@islishude  感谢反馈，这个已经勘误了。电子书是更新的。

**Comment by wangduanduan** [comment]
> 子书是更新的。

微信读书上还是错误的版本

<img width="1057" height="507" alt="Image" src="https://github.com/user-attachments/assets/4cf5406e-16db-420b-b192-6050421205f0" />
