### ISSUE TITLE
[第七章]7.4.1~7.4.4 代码清单的代码有重复

### ISSUE THREAD

**Issue by zhaozhiming** [ZhangHanDong/tao-of-rust-codes#197]
# 页码与行数
240~241 页

---

# 文本或排版错误

* 240 页 代码清单 7.4.1 最后的 main 函数和代码清单 7.4.2 重复
* 242 页 代码清单 7.4.3 最后的 main 函数和代码清单 7.4.4 重复

---

**Comment by ZhangHanDong** [comment]
@zhaozhiming 感谢反馈。 我抽时间对比一下。不过一般来说不会有重复，你看看上下文，是不是相关的代码，可能是复用一次。

**Comment by ZhangHanDong** [comment]
@zhaozhiming 感谢反馈。 我抽时间对比一下。不过一般来说不会有重复，你看看上下文，是不是相关的代码，可能是复用一次。

**Comment by zhaozhiming** [comment]
不知道是不是有意为之😂，个人感觉没有必要重复 main 函数哈

![image](https://user-images.githubusercontent.com/1436694/56498715-9a6cbb80-6535-11e9-99b8-810d11389325.png)

**Comment by ZhangHanDong** [comment]
好的，我看看

**Comment by mzji** [comment]
这里是为了把这个函数单独挑出来讲，这个重复也不算过分

**Comment by ZhangHanDong** [comment]
嗯，这里是故意单独挑出main函数说明。
