### ISSUE TITLE
关于函数生命周期参数的问题

### ISSUE THREAD

**Issue by tinycedar** [ZhangHanDong/tao-of-rust-codes#198]
1、“输出的生命周期参数长度必须不长于输入的生命周期长度”
2、“当从函数返回一个引用，返回值的生命周期参数需要与一个参数的生命周期参数相匹配”

由于上述两个条件的限制，那么返回值的生命周期等于输入生命参数中最小的。
既然这样，编译器就能直接判断出来了，为什么还需要手动添加生命周期参数呢？

**Comment by ZhangHanDong** [comment]
@tinycedar  编译器只能判断函数内部变量的生命周期，而不能判断跨函数传递引用的生命周期，所以需要生命周期参数来协助编译器去判断。可以继续往后面章节看看。
