### ISSUE TITLE
「第三章」 `3.1.4` 节 `类型大小` 增加一条注释 

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#20]
# 页码与行数

- 第54页
- 第8行

---

# 增加注释

> &str 存储与栈上，str 字符串存储与堆上。

建议增加一个注释说明 str 还有可能存储于程序的静态只读数据区内。

**Comment by ZhangHanDong** [comment]
@mzji 感谢反馈。

实际上，后面讲字面量字符串也专门提到了静态数据段。考虑到这是第2章，为了让大家过一遍语法。而内存管理的内容，都放到了第三章。

不过这里可以考虑加一句描述，感谢你的严谨。

**Comment by ZhangHanDong** [comment]
最终修改为：

> str字符串序列存储于程序的静态只读数据段或者堆内存中。
