### ISSUE TITLE
「第十三章」13.2.4 P497 #[may_dangle] 属性与dropck 模块下 #![feature(allocator_api] 编写错误

### ISSUE THREAD

**Issue by caitlingao** [ZhangHanDong/tao-of-rust-codes#202]
# 页码与行数

- 第497页
- 第27行
#[may_dangle]属性与dropck 模块下的这段描述`所以需要在 Nightly Rust 版本之下使用 #![feature(allocator_api]特性` 中的 `#![feature(allocator_api]` 编写错误，应该为 `#![feature(allocator_api)]`

**Comment by ZhangHanDong** [comment]
@caitlingao 感谢反馈

**Comment by ZhangHanDong** [comment]
@caitlingao 你写的这俩有啥区别吗？
