### ISSUE TITLE
「第三章」 `3.4.3` 节 `抽象类型` 中的错误

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#21]
# 页码与行数

- 第72页
- 图 3-6

---

# 概念错误

图中显示 trait object 的 vtable 被存放在堆中，但这是错误的：vtable 一般放在程序的静态只读数据区中，而非堆中

**Comment by ZhangHanDong** [comment]
@mzji 

这里是不是你理解错了？我讲的是TraitObject这个结构体，vtable是一个指针，指向堆。

**Comment by mzji** [comment]
就是这里有问题：vtable 为什么会指向堆？虚函数表不会在堆里啊！

**Comment by ZhangHanDong** [comment]
@mzji 好，我再确认下

**Comment by ZhangHanDong** [comment]
修改图片3-6
