### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Planet6174** [ZhangHanDong/tao-of-rust-codes#210]
我没时间翻完所有的 issue, 所以不知道有没有和之前的撞了……（我手上的是 2019.1 第 2 次印刷的版本）

【2.8.3 链表】代码下面的第一行 LinedList 应为 LinkedList
【8.2.1 可增长数组 - 与排序和比较相关的 trait】第 2 行 triat 应为 trait  
【附录 A.1】PlayGroud 应为 PlayGround（←你好像打错了四次）, Beat 应为 Beta  
小问题：P63 代码 3-22 第一行 `Add <RHS, Output >`，`Output` 和 `>` 中间多了个空格  
小问题：P55 代码报错信息的下划线（就是 `^^^^^` 这种东西）和上面一行的内容没对齐，这好像是由于两端对齐造成的，强烈建议书中所有代码的对齐方式改为左对齐

还有几个吐槽
图片 3-9 5-5 12-7 汉字太小  
图片 5-8 英文太小  
图片 6-3 中汉字字体不统一  
（出书的话应该有美编负责修图的吧……您自己整的图的质量有点糟糕……建议您找个美编把图片好好修整一下）

**Comment by ZhangHanDong** [comment]
@Planet6174  感谢反馈。 那些问题我来对照一下。至于图的问题，我会反映给出版社，美编也不好修改我的图，而且为了保证不要印的太厚，图片大小也会缩减一下。期待后面的印刷版可以更好点。

**Comment by ZhangHanDong** [comment]
一些typo已经修改，图的问题，后面统一修正吧。
