### ISSUE TITLE
「第三章」代码清单3-40 代码错误

### ISSUE THREAD

**Issue by QiBaobin** [ZhangHanDong/tao-of-rust-codes#213]
1. 两个方法都不是对象安全的,所以后面两个例子即使改正了一个还是不安全的. 注释有误.
2. 第二个例子拆分两个trait都叫Foo, 第一个应该叫Bar. 同样, 两个方法都是不安全的话, 拆分就没有意义了.

所以,感觉第一个方法应该改成一个对象安全的才对!

```rust
trait Foo {
    fn bad<T>(&self, x: T); // -> fn good(&self);
    fn new() -> Self;
}
```

**Comment by ZhangHanDong** [comment]
@QiBaobin  感谢反馈。这个问题还在勘误中，最近会总结出一个结果。不过前面也有一些讨论，可以选择「精选」label来查看。

**Comment by ZhangHanDong** [comment]
https://github.com/ZhangHanDong/tao-of-rust-codes/issues/51  

合并

**Comment by ZhangHanDong** [comment]
归并到了 #137
