### ISSUE TITLE
[第四章] 4.2.4 文字错误

### ISSUE THREAD

**Issue by QiBaobin** [ZhangHanDong/tao-of-rust-codes#214]
# 页码与行数

- 第115页
- 4.2.4 第1行

---

# 文本或排版错误

> 结构体(Enum) 应为 结构体(Struct), 枚举体(Enum)

**Comment by ZhangHanDong** [comment]
@QiBaobin  你是不是看的第一次印刷的书？  这个应该勘误过了，我再排查一下，感谢反馈。

**Comment by QiBaobin** [comment]
@ZhangHanDong 是第一次印刷! 哪里有勘误列表吗？

**Comment by QiBaobin** [comment]
找到了，https://github.com/ZhangHanDong/tao-of-rust-fix

**Comment by ZhangHanDong** [comment]
@QiBaobin  当前仓库就是勘误列表。你找的那个是我打算重新整理的，现在还没来得及搞。 你在随书源码的issues里，可以按章节label来查询，cloese状态是勘误过的，open状态是待勘误的。「精选」label的内容是推荐重点阅读的。
