### ISSUE TITLE
[第五章] 5.1

### ISSUE THREAD

**Issue by QiBaobin** [ZhangHanDong/tao-of-rust-codes#215]
# 页码与行数

- 第120页

---

# 文本或排版错误
感觉把值类型和栈绑定, 引用和堆绑定有点欠妥. 毕竟我们可以解引用堆数据和引用栈数据, 我们可以创建指向栈的指针, 也可以使用堆里面的数据.

```rust

let i = Box::new(1);

// *i is value

let n = 32;

// &n is reference

```

还有后面的深浅复制, 区别应该是, 按位复制, 还是尊重类型, 比如同样复制指针指向的另一块数据.

**Comment by ZhangHanDong** [comment]
@QiBaobin 是的，你说的没问题。  issues里选择「精选」label，有这部分内容的更详细的勘误。
