### ISSUE TITLE
【第二章】2.4.2 内容建议

### ISSUE THREAD

**Issue by riversyang** [ZhangHanDong/tao-of-rust-codes#217]
2.4.2 中在第 19 页的第一段介绍【变量遮蔽】时，建议将本质上的原理解释清楚：
之所以“最终的变量 v 的值是由第二个变量定义所决定的”，是因为由于通过花括号声明了作用域，所以花括号内的变量 v 和花括号外的变量 v 实际上是两个变量，本质上是两个内存地址，仅仅名字相同而已，所以对它们的操作是不会互相影响的。可以借助书中刚刚介绍过的显示变量内存地址的方法来验证这一点。

```rust
fn main() {
  let v = "hello rust!";
  let p1 = &v;
  println!("{:p}", p1);
  {
    let v = "hello world!";
    let p2 = &v;
    println!("{:p}", p2);
  }
}
```

**Comment by ZhangHanDong** [comment]
@riversyang 感谢反馈

**Comment by ZhangHanDong** [comment]
@riversyang  这个其实和作用域也没有关系，主要是let，重新绑定。现已修订。
