### ISSUE TITLE
「第四章」增补 `4.1` 节 `通用概念` 中的限定

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#22]
因为 `4.1` 节中讲述的大量内容仅适用于 x86 平台，建议添加“以下以 x86 为例，简单的说明通用处理器平台的虚拟内存系统”等字样，以免混淆（MIPS 的虚拟地址空间管理很不相同；其他 ISA 中也不存在 ESP / EBP 这样的寄存器；等等）

**Comment by ZhangHanDong** [comment]
@mzji

你说的这个情况，我下面加了注释了呀。
