### ISSUE TITLE
【第十一章】 nodejs不是语言

### ISSUE THREAD

**Issue by huangjj27** [ZhangHanDong/tao-of-rust-codes#220]
# 页码与行数
第一次印刷版，364页11.1.2 小节第二段第4行

---

# 文本或排版错误

> 比如Node.js，也就是第一个事件驱动编程模型语言

 Node.js应该是基于事件驱动编程模型的JavaScript运行时吧

**Comment by ZhangHanDong** [comment]
@huangjj27 感谢反馈。

**Comment by ZhangHanDong** [comment]
删掉那句话了
