### ISSUE TITLE
「第四章」 `4.2.3` 节 `内存泄漏与内存安全` 中的错误： `RefCell` 不是智能指针

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#23]
# 页码与行数

- 第112页
- 第11~12行

---

# 概念错误

> 不过， Rust 提供了另外一个智能指针 `RefCell<T>` …

`RefCell<T>` 不是智能指针，其内部的占用标记与 `T` 的数据是存放在一起的，详情可参见 [Rust Container Cheatsheet](https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/edit#slide=id.p)

`RefCell<T>` 的布局：
![6ctkx a3a86 ter 8w5 bsk](https://user-images.githubusercontent.com/23279426/50727096-d9c2f800-1150-11e9-856e-9f0ab17f712a.png)
作为对比， `Rc<T>` 的布局：
![05 4e01e8yfqk x 248 1 0](https://user-images.githubusercontent.com/23279426/50727113-14c52b80-1151-11e9-94af-2accce9f7a79.png)

**Comment by ZhangHanDong** [comment]
@mzji 感谢反馈。

这里确实需要修正。
