### ISSUE TITLE
[附录A] A.4 编辑器介绍中Emacspace为笔误？

### ISSUE THREAD

**Issue by cireu** [ZhangHanDong/tao-of-rust-codes#230]
# 页码与行数
- 547页
- 第3行
---

# 文本或排版错误

文中提到编辑器”Emacspace“，然而我在网络上并未搜索相关内容，您是否指的是[Spacemacs](https://github.com/syl20bnr/spacemacs)?

另外，如果您指的是Spacemacs，我觉得Spacemacs作为Emacs的一份配置，不宜单独列出。

**Comment by ZhangHanDong** [comment]
@cireu 感谢反馈，Emacspace确实是笔误，我想推荐的是spacemacs。
