### ISSUE TITLE
[第十章] 10.1 lto中文翻译“连接时间的优化” 可能会产生歧义

### ISSUE THREAD

**Issue by cireu** [ZhangHanDong/tao-of-rust-codes#232]
# 页码与行数

- 第335页
- 倒数第3-4行

---

# 文本或排版错误

书中提到“连接时间的优化lto”，这样表述可能会使读者认为是“连接过程的时间”上的优化，而并非其本意”在连接时“进行的优化

**Comment by ZhangHanDong** [comment]
@cireu 感谢反馈。这个应该是排版的锅了，我记得我写的是「链接时优化」。
