### ISSUE TITLE
【第四章】4.2.4 图片类型错误 图 4-11

### ISSUE THREAD

**Issue by Michael2008S** [ZhangHanDong/tao-of-rust-codes#237]
# 页码与行数

- 第116页
- 图片中的文字

---

# 文本或排版错误

` b:Box<u32>`

应该是：

` b:Box<u64>`

---

**Comment by ZhangHanDong** [comment]
@Michael2008S 感谢反馈

**Comment by dwing4g** [comment]
图里box指针指向的明显是4个字节空间, 不如把结构体A里的定义改为b: Box<u32>

**Comment by zydxhs** [comment]
我买的是第四版印刷，没发现错误。
是图 4-11 已经是 b: Box<u64> 了；图 4-12（p117）跟代码 4-22 也是一致的。

**Comment by ZhangHanDong** [comment]
@zydxhs 感谢反馈
