### ISSUE TITLE
「第五章」「C++对象作为右值参与赋值时...」的描述问题

### ISSUE THREAD

**Issue by ZhangHanDong** [ZhangHanDong/tao-of-rust-codes#238]
# 页码与行数

- 代码清单5-4 上面一段

![Screen Shot 2019-08-14 at 09 05 00](https://user-images.githubusercontent.com/27893/62987502-ad9ff000-be72-11e9-9b5b-8b6b31290f51.png)

### 错误说明

> 既然作为右值参与赋值即移动构造函数/移动赋值函数，实现起来也是move内部指针而不是复制。要深度复制用左值语义的拷贝构造函数/拷贝赋值函数。
> 当对象作为右值参与赋值的时候，一般会建议开发者自定义实现移动构造函数/移动赋值函数

**Comment by ZhangHanDong** [comment]
一般对于vector这种类型，如果使用右值引用，需要显式地标记移动构造函数是否可以安全地使用

**Comment by zydxhs** [comment]
在可以用**移动语义**的地方，但程序员又没有定义**移动语义**的赋值运算符重载时，C++会转而调用**复制语义**的运算符重载。

**Comment by ZhangHanDong** [comment]
@zydxhs  这个应该已经勘误了，我回头再检查下，感谢反馈
