### ISSUE TITLE
【第二章】关于条件表达式的一个表达问题

### ISSUE THREAD

**Issue by RocFang** [ZhangHanDong/tao-of-rust-codes#239]
汉东老师，这个问题我在微信群里已经跟您求证过，但事后觉得还是在这里整理一下更好，留个记录。

# 位置

第2.5.1节条件表达式的第一段。（抱歉，我在写这个issues的时候书不在手边，只用手机在相关段落拍了一张不全的照片，页码没拍进去。所以没有按照您的issues模版来。）

# 原文

>条件表达式一定会有值，所以if表达式的分支必须返回同一个类型的值才可以。这也是Rust没有三元操作符?:的原因。

# 沟通过程

我的问题：

>汉东老师，在2.5.1条件表达式这一节，书里说 “表达式一定会有值，所以if表达式的分支必须返回同一个类型的值才可以。这也是Rust没有三元操作符?:的原因。”
>
>读起来感觉这一句话有点问题，感觉您想表达因为三元操作符可能会返回不同类型的值，所以才没有支持三元操作符。
>
>一方面，在c里面，虽然int a = 1 == 2 ? 2 : “aa”;这样的语句编译器不会报错,但是会报类型不匹配和一个从指针到整数的类型转换的警告，而且这个其实跟三目运算本身没关系，直接用int a = “aa”,也是会涉及到相同的警告，即类型不匹配和一个从指针到整数的类型转换。
>
>另一方面，我查了一下rust以前的issues，比如 https://github.com/rust-lang/rfcs/issues/1362 （不止这一个），里面的讨论也大部分都是基于有没有必要在if else满足条件的情况下引入一个三目操作，而且rust之前的版本里本来是有三目，后来有觉得没必要所以去掉了。
>
>总之我想表达的是可能rust没有三元操作符不是因为这个原因，不知道我理解有没有问题。谢谢：）

您的回复：

>你想太多了。我想表达的就是两点：
>
>1. if是个表达式。表达式自然要返回同一个类型的值。
>2. 有了这个表达式就没必要引入三元操作符了（所以，没有三元操作符），你看看Rust的语法，基本上是避免同一件事引入多种方法。再加上三元操作符中的两个符号「:」和「?」，在Rust里会破坏一致性。

# 我的小结

您的东西在知识上我本来都是懂的，但是为什么我会把您的本意想偏了呢，我仔细思考一下，原因在于您本来想表达的是因为条件表达式一定会有值，所以会导致两个结果，其一是要返回同类型的，其二是没有必要引入三元操作符。这两个结果是**并列**的，但是这个断句读起来有可能会让人觉得您想表达第二个结果是由第一个结果所导致的，这就会像我一样觉得有点奇怪。您看需不需要稍微调整一下，比如改成：

>条件表达式一定会有值，所以if表达式的分支必须返回同一个类型的值才可以。也正因为它一定会有值，Rust不需要存在三元操作符:?。

其实我自己都觉得这个我这个点有点吹毛求疵了,严格来说您的原始表达也没问题:)

**Comment by ZhangHanDong** [comment]
@RocFang  有个记录也挺好。你也不算吹毛求疵吧，学习过程中，要对自己的理解负责，很正常。希望有更多反馈，我很喜欢讨论。
