### ISSUE TITLE
「第四章」 `4.2.4` 节 `复合类型的内存分配与布局` 中的中英文对应错误

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#24]
# 页码与行数

- 第115页
- 第24行

---

# 文本或排版错误

> …… 那么，结构体（Enum）或联合体（Union）是被分配在哪的呢？

应为

> …… 那么，结构体（Struct）、枚举（Enum）和联合体（Union）又是被分配在哪的呢？

下面还有同样的误植

**Comment by ZhangHanDong** [comment]
@mzji 感谢反馈。

这里确实需要修正。
