### ISSUE TITLE
【第八章】代码清单8-5，to_lowercase和to_uppercase的API变更为to_ascii_lowercase和to_ascii_uppercase

### ISSUE THREAD

**Issue by yunweb** [ZhangHanDong/tao-of-rust-codes#240]
# 页码与行数

- 第248页
- 代码清单8-5
- 第9行和第10行

### 错误信息

```rust
error: 
assert_eq!('i', 'I'.to_lowercase());
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected char, found struct `std::char::ToLowercase`

error:
assert_eq!('B', 'b'.to_uppercase());
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected char, found struct `std::char::ToUppercase`
```

---

# API变更

> 第9行的to_lowercase变更为to_ascii_lowercase
> 第10行的to_uppercase变更为to_ascii_uppercase

---

# 正确代码

```rust
assert_eq!('i', 'I'.to_ascii_lowercase());
assert_eq!('B', 'b'.to_ascii_uppercase());
```

**Comment by ZhangHanDong** [comment]
@yunweb 感谢反馈

**Comment by ZhangHanDong** [comment]
不要close先

**Comment by by23** [comment]
第248页
代码清单8-5
assert!(!'¾'.is_alphanumeric());
`thread 'main' panicked at 'assertion failed: !'¾'.is_alphanumeric()', 8-5.rs:20:5`

**Comment by by23** [comment]
断言
`assert!('¾'.is_alphanumeric());`
和
`assert!('¾'.is_numeric());`
正确。

**Comment by by23** [comment]
> 
    assert_eq!(Some('i'), 'I'.to_lowercase().next());
    assert_eq!(Some('B'), 'b'.to_uppercase().next());

to_lowercase()和to_uppercase()会返回一个迭代器

**Comment by ZhangHanDong** [comment]
@by23 感谢反馈

**Comment by ZhangHanDong** [comment]
```rust
assert!(!'¾'.is_alphanumeric());
```
现在应该是 ：
```rust
assert!('¾'.is_alphanumeric());
```

这应该是api变更，之前认为 `'¾'`不是字母，现在认为是了。
