### ISSUE TITLE
代码拼写错误 第四章 代码清单4-11

### ISSUE THREAD

**Issue by asingingbird** [ZhangHanDong/tao-of-rust-codes#243]
# 页码与行数

- 第108页
- 代码清单4-11

---

# 文本或排版错误

> 暂无

---

# 代码错误
代码清单4-11有两处单词拼写错误
let x = S(1);
println!("crate x: {:?}", x);
这里应该是create，笔误写成了crate。

### Rust版本

```
$ rustc -V
rustc 1.32.0-nightly (8b096314a 2018-11-02)
```

### 错误信息

```rust
error: xxxx
xxxx
xxxx
```

**Comment by ZhangHanDong** [comment]
@asingingbird 感谢反馈
