### ISSUE TITLE
「第五章」Typo: RwLock 误写作 RewLock

### ISSUE THREAD

**Issue by HunDunDM** [ZhangHanDong/tao-of-rust-codes#248]
# 页码与行数

- 5.7 并发安全与与所有权（接近章节结尾处）
- Kindle阅读位置 3481/10576

---

# 文本或排版错误

> Rust提供了一些线程安全的同步机制，比如Arc<T>、Mutex<T>、R~~e~~wLock<T>和Atomic系列类型。下面是关于这些类型的简要说明。

此处 RewLock 应为 RwLock

---

**Comment by ZhangHanDong** [comment]
@HunDunDM 感谢反馈

**Comment by HunDunDM** [comment]
标错了，是第五章的内容

**Comment by ZhangHanDong** [comment]
@HunDunDM 已修正
