### ISSUE TITLE
「第五章」 `5.2` 节 `所有权机制` 中图示表意问题

### ISSUE THREAD

**Issue by mzji** [ZhangHanDong/tao-of-rust-codes#25]
# 页码与行数

- 第123页
- 图 5-2

---

# 文本或排版错误

图中箭头由堆指向栈，我感觉应该反过来，由栈指向堆

**Comment by ZhangHanDong** [comment]
@mzji 

其实你说的也对。
不过我在画这个图的时候，是想用箭头表示「堆数据“5”的指针从这里移动向了那里」的意思。
其他类似的图，都是栈指向堆，考虑到全书的统一，这个地方需要修正。

**Comment by mzji** [comment]
一般来说箭头都是从指针引出，箭头朝向被指针指向的数据

**Comment by ZhangHanDong** [comment]
图已修订
