### ISSUE TITLE
张老师，你的rust编程之道还要出下一个版本不?

### ISSUE THREAD

**Issue by joyoes** [ZhangHanDong/tao-of-rust-codes#256]
张老师，你好！我问一下，你这个rust编程之道版本的书籍中，有些已知的BUG没有表述清楚的，还有现在rust已经出了1.39版本的，又新增了await的异步支持这些功能！我问一下，你是否有计划再出下一个版本的rust编程之道，我很期待！

**Comment by ZhangHanDong** [comment]
会的，不过得明年了。
第二版的内容不仅仅是针对Rust新的特性增加新的内容，更会是一次整体性的升级和重构。
感谢你的期待，我自己也非常期待。

**Comment by ZhangHanDong** [comment]
https://github.com/ZhangHanDong/tao-of-rust-codes/issues/257 

建了个新的issues收集第二版建议，你也可以写到这个新issues里
