### ISSUE TITLE
[第二章] 26页基本数字类型数值范围排版错误

### ISSUE THREAD

**Issue by dispensable** [ZhangHanDong/tao-of-rust-codes#26]
# 页码与行数

- 第26页
- 第27行及以后

---

# 文本或排版错误

> u16，数值范围为 0 ~ 2^(16 -1 )

应为 0 - （2^16 - 1）

下同，应该是印刷的时候把-1当成指数部分了。见 [无符号数](https://zh.wikipedia.org/wiki/%E6%97%A0%E7%AC%A6%E5%8F%B7%E6%95%B0)

**Comment by ZhangHanDong** [comment]
@dispensable

感谢反馈。电子版里修正它。
