### ISSUE TITLE
[第九章] unwrap拼写错误

### ISSUE THREAD

**Issue by Jackeyzhe** [ZhangHanDong/tao-of-rust-codes#266]
# 页码与行数

- 第298页
- 倒数第1行

---

# 文本或排版错误

> 标准库中还提供了unwarp系列方法

拼写错误，应该是unwrap

**Comment by ZhangHanDong** [comment]
@Jackeyzhe 感谢反馈。

 你看书是不是跳着看的？「和类型」是一个整体的词，参见前面的第八章。

**Comment by Jackeyzhe** [comment]
第八章确实没看完，抱歉抱歉。我更新一下issue
