### ISSUE TITLE
13.3 和其他语言交互 句法不顺、意思不明

### ISSUE THREAD

**Issue by xie-jirong** [ZhangHanDong/tao-of-rust-codes#268]
# 页码与行数 P521 第5段
---

# 文本描述错误
![image](https://user-images.githubusercontent.com/52877065/71898248-c8616100-3193-11ea-9d8d-31a020064cb4.png)

> 该类型会产生以“\n”字符数组的引用。
何义？ 以"\n"字符怎么的数组？结尾吗？是\n or \0 ？

**Comment by ZhangHanDong** [comment]
@xie-jirong 感谢反馈，这个是笔误，应该之前改过了。
