### ISSUE TITLE
排版错误(类似->类型)

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#271]
# 页码与行数

- 第86页
- 第4行

---

# 文本或排版错误
> match x.as_ref(), String 类型提供了 as_ref 方法来返回一个&str ***类似***，该方法定义于 AsRef trait 中。

“类似“应改为“类型”。

**Comment by ZhangHanDong** [comment]
@zydxhs 感谢反馈，你的书是第几次印刷版呢？

这个好像已经修改了，我再确认确认。

**Comment by zydxhs** [comment]
第4次印刷。

**Comment by xiaods** [comment]
第二次印刷版本有次错误。

**Comment by ZhangHanDong** [comment]
@xiaods 感谢反馈
