### ISSUE TITLE
[第四章] 代码清单4-3 代码返回结果和后面的描述有误

### ISSUE THREAD

**Issue by xiaods** [ZhangHanDong/tao-of-rust-codes#273]
# 103页，代码清单4-3 代码返回结果和后面的描述有误

[play运行链接](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=40b5cf1bc43d3b350815f79bf90e9311)

书中说8，实际返回为16。后面描述中说以联合体最大字长变量f3为返回值。实际为3个变量字长之和返回。

**Comment by ZhangHanDong** [comment]
@xiaods 感谢反馈

**Comment by zydxhs** [comment]
@xiaods @ZhangHanDong 
代码清单中写的是 union ，不是 struct，因此 union 的大小是 8 字节。

**Comment by xiaods** [comment]
@zydxhs my bad. close it.
