### ISSUE TITLE
第4章 结构体字段重排首地址错误 第1版 第4次印刷

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#274]
# 页码与行数

- 第116页
- 第8行（图4-11下面第2段）

---

# 文本或排版错误

> ```
> struct A {
>     a: u32,
>     b: Box<u64>,
> }
> ```
> 当结构体A在中有实例被初始化时，该结构体会被放到栈中，首地址为**第一个成员变量a**的地址，长度为16字节。

应该是“第二个成员变量 b ”的地址。

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b862aff10db0b86682c44a7a07818ccf

**Comment by ZhangHanDong** [comment]
@zydxhs  感谢反馈
