### ISSUE TITLE
代码清单5-6注释位置错误 第1版 第4次印刷

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#275]
# 页码与行数

- 第125页
- 代码清单 5-6

---

# 代码错误

> #[derive(Debug)]
> struct A {
>     a: i32,
>     b: i32,
> }
> fn main() {
>     let a = A { a: 1, b: 32 };
>     let b = a; // error[E0382]: use of moved value: `a`
>     println!("{:?}", a);
> }

注释应该放在 `println` 这一行。

**Comment by ZhangHanDong** [comment]
感谢反馈
