### ISSUE TITLE
【建议】示例代码很多应该都还有改进余地

### ISSUE THREAD

**Issue by thelastfantasy** [ZhangHanDong/tao-of-rust-codes#277]
比如[这里](https://docs.rs/tao-of-rust/1.0.2/tao_of_rust/ch05/smart_pointer/fn.cow.html#%E6%99%BA%E8%83%BD%E6%8C%87%E9%92%88%E5%92%8C%E6%89%80%E6%9C%89%E6%9D%83-cow%E5%86%99%E6%97%B6%E5%A4%8D%E5%88%B6)
cargo clippy 跑了一下提示fold(0, |acc, &n| acc + n)可用sum()来代替，类似这样的可改进的示例应该还有不少吧
同时也是被clippy吓了一跳，这样的代码都能检查出来真是厉害

**Comment by ZhangHanDong** [comment]
@thelastfantasy  感谢反馈。

示例代码首先为了有教学效果，当然还有改进空间，但也不适合用 cargo clippy跑。
