### ISSUE TITLE
[第五章]文本错误

### ISSUE THREAD

**Issue by Jackeyzhe** [ZhangHanDong/tao-of-rust-codes#278]
# 页码与行数

- 第119页
- 第15行

---

# 文本或排版错误

> 代码清单 5-1：C++的RAI机制存在的安全隐患示例

应为RAII机制

---

**Comment by ZhangHanDong** [comment]
@Jackeyzhe 感谢反馈

**Comment by zydxhs** [comment]
第四次印刷 已经修复。

**Comment by ZhangHanDong** [comment]
@zydxhs  感谢反馈
