### ISSUE TITLE
[第五章]智能指针小节的一些文本错误

### ISSUE THREAD

**Issue by Jackeyzhe** [ZhangHanDong/tao-of-rust-codes#279]
# 页码与行数

- 第147页
- 第1行

# 文本或排版错误

> 代码清单5-44：智能指时Box<T>独占所有权
智能指时 ->  智能指针

---

- 第147页
- 第23行？不知道数错没有

# 文本或排版错误

> 之所可以解引用，是因为Box<T>实现了deref方法。
不太顺，应该是“之所以可以解引用”吧
---

- 第148页
- 第14行

# 文本或排版错误

> 代码清单5-48：Box<T>的原码实现
原码 ->  源码
---

**Comment by ZhangHanDong** [comment]
@Jackeyzhe  感谢反馈。你看的是第几次印刷版？

**Comment by Jackeyzhe** [comment]
> @Jackeyzhe 感谢反馈。你看的是第几次印刷版？

2019年第一版第一次印刷

**Comment by ZhangHanDong** [comment]
好的

**Comment by zydxhs** [comment]
> 147 页：代码清单5-44：智能指时Box独占所有权

第四次印刷 已经修复。
其它两处错误，等待下次印刷修复了
