### ISSUE TITLE
2.1.3 核心库 标点符号问题

### ISSUE THREAD

**Issue by limuyuan** [ZhangHanDong/tao-of-rust-codes#280]
# 页码与行数

- 第12页
- 2.1.3 核心库 第4行
- 2019年1月第1版
- 2020年3月第6次印刷
---

# 文本或排版错误

> 可以通过在模块顶部引入#![no_std]来使用核心库。，

**核心库**三个字后面有一个逗号和一个句号，请考虑去掉一个

**Comment by ZhangHanDong** [comment]
感谢反馈
