### ISSUE TITLE
any和fold参数问题 第6章

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#282]
# 页码与行数

- 第四次印刷
- 第208页
- 第1行， 倒数第2行

---

# 文本或排版错误

> any 和 fold 传入的闭包的参数是一个引用。
> 在代码清单 6-80 的第 3 行中

- any 闭包参数是引用，fold 闭包参数是 mut self，不是引用。

- 代码清单 6-80 没有使用 next 方法，应该是 6-74 或者 6-75 ？

- 代码清单 6.81 关于 fold 的函数签名与实现，也跟源码不一致。

Rust 版本：1.42

**Comment by ZhangHanDong** [comment]
感谢反馈，我抽空确认下。

**Comment by ZhangHanDong** [comment]
这个没办法改了，Rust源码变化太大了。 这些读者自行确认吧，但是书中对any和fold所传达的意思是不变的。
