### ISSUE TITLE
第8章 8.1.6节 “替换字符的个数”表述不准确 第1版 第四次印刷

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#286]
# 页码与行数

- 第261页
- 第7行

---

# 文本或排版错误

> 与之相对应的 replacen 方法，支持通过第三个参数来指定**替换字符的个数**。

**替换字符的个数** 应该是 **替换次数**。

**Comment by ZhangHanDong** [comment]
@zydxhs 标题上加上具体章节
