### ISSUE TITLE
[十三章] 代码清单 13-13 执行报错

### ISSUE THREAD

**Issue by liy010** [ZhangHanDong/tao-of-rust-codes#291]
# 代码错误
其他代码没问题，这一段执行的时候出现错误
```
let x = vec![0, 1, 2, 3];
let y = &x as *const Vec<i32>;
unsafe {
    assert_eq!(y.read(), [0,1,2,3]);
}
```
### Rust版本

```
rustc 1.43.0 (4fb7144ed 2020-04-20)  macos 10.15.4
rustc 1.43.0 (4fb7144ed 2020-04-20)  ubuntu 20.04
```

### 错误信息

```
MacOS
example(23006,0x105530dc0) malloc: *** error for object 0x7f868d405b10: pointer being freed was not allocated
example(23006,0x105530dc0) malloc: *** set a breakpoint in malloc_error_break to debug

Ubuntu
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by zydxhs** [comment]
win10 x64 + rustc 1.43 表示代码可以正常运行。

**Comment by ZhangHanDong** [comment]
噢？ 我抽空看看啥情况

**Comment by ZhangHanDong** [comment]
@liy010  @zydxhs  这段代码出了UB

**Comment by ZhangHanDong** [comment]
```rust
fn main() {
    let x = [0, 1, 2, 3];
    let y = &x as *const [i32; 4];
    unsafe {
        assert_eq!(y.read(), [0,1,2,3]);
    }
}
```

这样没问题。

**Comment by ZhangHanDong** [comment]
```rust
fn main() {
    let x  = vec![0, 1, 2, 3];
    let y = &x as *const Vec<i32>;
    unsafe {
        assert_eq!(std::ptr::read(y), [0,1,2,3]);
    }
    std::mem::forget(x); // 增加这一行即可
}
```

上面的问题在于：双重释放。

x在调用结束释放内存，但是还有一个原生指针，也会被释放，所以需要先把 `x`的所有权forget掉，就只能释放一次了。

@liy010 @zydxhs

**Comment by ZhangHanDong** [comment]
这个问题需要在第二版里详细描述，暂时在第7次印刷版中增加对此issues的引用

**Comment by ZhangHanDong** [comment]
```rust
#[derive(Debug)]
struct My;

impl Drop for My {
    fn drop(&mut self) {
        println!("Dropping!");
    }
}

fn main() {
    let x  = My;
    let y = &x as *const My;
    // std::mem::forget(x);
    unsafe {
        let a = std::ptr::read(y);
        println!("{:?}", a);
    }
}
```

输出：

```
My
Dropping!
Dropping!
```

**Comment by zydxhs** [comment]
> ```rust
> fn main() {
>     let x = [0, 1, 2, 3];
>     let y = &x as *const [i32; 4];
>     unsafe {
>         assert_eq!(y.read(), [0,1,2,3]);
>     }
> }
> ```
> 
> 这样没问题。

这段代码，win10 x64 + rustc v1.45.2 编译失败：
```
error[E0606]: casting `&std::vec::Vec<i32>` as `*const [i32; 4]` is invalid
 --> src\main.rs:3:13
  |
3 |     let y = &x as *const [i32; 4];
  |             ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ZhangHanDong** [comment]
> > ```rust
> > fn main() {
> >     let x = [0, 1, 2, 3];
> >     let y = &x as *const [i32; 4];
> >     unsafe {
> >         assert_eq!(y.read(), [0,1,2,3]);
> >     }
> > }
> > ```
> > 
> > 
> > 这样没问题。
> 
> 这段代码，win10 x64 + rustc v1.45.2 编译失败：
> 
> ```
> error[E0606]: casting `&std::vec::Vec<i32>` as `*const [i32; 4]` is invalid
>  --> src\main.rs:3:13
>   |
> 3 |     let y = &x as *const [i32; 4];
>   |             ^^^^^^^^^^^^^^^^^^^^^
> ```

@zydxhs 这个问题你报给 Rust 官方吧，去官方仓库那发个 issues。 估计是windows支持出了啥问题。

**Comment by zydxhs** [comment]
> > ```rust
> > fn main() {
> >     let x = [0, 1, 2, 3];
> >     let y = &x as *const [i32; 4];
> >     unsafe {
> >         assert_eq!(y.read(), [0,1,2,3]);
> >     }
> > }
> > ```
> > 
> > 
> > 这样没问题。
> 
> 这段代码，win10 x64 + rustc v1.45.2 编译失败：
> 
> ```
> error[E0606]: casting `&std::vec::Vec<i32>` as `*const [i32; 4]` is invalid
>  --> src\main.rs:3:13
>   |
> 3 |     let y = &x as *const [i32; 4];
>   |             ^^^^^^^^^^^^^^^^^^^^^
> ```

又验证了一次，编译成功了。估计是增量编译导致的问题。
