### ISSUE TITLE
第11章 11.4节 ARM平台函数命名 第1版 第4次印刷

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#292]
# 页码与行数

- 第1433页
- 第6行

---

# 文本或排版错误

> 也有其他类型 ，这里不再赘述。像 ARM 平台支持的类型命名就 比较直观，比如：
> •  float32x2_t，代表 64 位宽度的 2 组打包 f32 向量类型。
> •  float32x4_t，代表 128 位宽度的 ***2 组打包 f32 向量类型。***
> •  int32x2_t， 代表 64 位宽度的 2 组打包 i32 向量类型。
> •  int32x4_t， 代表 128 位宽度的 ***2 组打包 i32 向量类型。***

如上 **第二和第四** 行，根据第1和第3行的描述，应该是 **_4 组_** 打包 f32/i32 向量类型”。

**Comment by ZhangHanDong** [comment]
感谢反馈，这应该是笔误。
