### ISSUE TITLE
第12.2 节 “编写过程宏必须要求”排版不正确 第1版 第4次印刷

### ISSUE THREAD

**Issue by zydxhs** [ZhangHanDong/tao-of-rust-codes#293]
# 页码与行数

- 第459页
- 倒数第4行

---

# 文本或排版错误

> 编写过程宏 **必须要求** 放到 proc_macro 类型的 lib 包中。

该句改成下面这样，语意更通畅：
> 编写过程宏 **要求必须** 放到 proc_macro 类型的 lib 包中。

**Comment by ZhangHanDong** [comment]
多谢建议
