### ISSUE TITLE
本书是否有计划跟进Rust 2018 edition

### ISSUE THREAD

**Issue by longwusha** [ZhangHanDong/tao-of-rust-codes#3]
社区消息显示Rust 2018 edition首个正式版本rust 1.31将于12.6发布。

相对于Rust 2015 edition，编译器的使用和语言特性均有不小变化，本书是否有计划跟进Rust 2018 edition，还是准备在第二版中在进行跟进，谢谢！

**Comment by ZhangHanDong** [comment]
@longwushua

感谢你的关注。本书就是为了跟进Rust 2018才推迟到12月份后出版，否则在今年4月份就早已面世了。 而且你也可以看看代码，代码也早已跟进Rust 2018.
