### ISSUE TITLE
「第五章」 `5.8` , 代码清单5-60

### ISSUE THREAD

**Issue by Kreedzt** [ZhangHanDong/tao-of-rust-codes#304]
# 代码错误
代码过期

现版本Rust可以编译通过

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2aec4372c130347325200249f5c1235a)

**Comment by ZhangHanDong** [comment]
为啥关掉了？

**Comment by Kreedzt** [comment]
本节后面说明了...

**Comment by ZhangHanDong** [comment]
ok
