### ISSUE TITLE
【第十三章】13.2.1 原生指针 - 使用offset方法  表述不清晰

### ISSUE THREAD

**Issue by bailaobo** [ZhangHanDong/tao-of-rust-codes#316]
# 13.2.1 原生指针 - 使用offset方法 
---

# 表述不清晰

> “offset 就是指偏移量，通过该方法可以指定相对于指针地址的偏移字节数”

指针的偏移(加减)，实际加减的是一个单位(sizeof(T))，不是字节数。
// offset 方法的注解
Calculates the offset from a pointer.
count is in units of T; e.g., a count of 3 represents a pointer offset of 3 * size_of::<T>() bytes.

---

**Comment by ZhangHanDong** [comment]
@bailaobo 感谢反馈。 你说的是offset的计算方法吧，最终不还是字节数？
