### ISSUE TITLE
请问什么是`按位复制`，第一次听到这个概念？

### ISSUE THREAD

**Issue by Aaron009** [ZhangHanDong/tao-of-rust-codes#318]
它是深度拷贝的意思吗？

我还发现一个问题。书中说花括号创建词法作用域，词法作用域我是第一次看到，以前我学习其他编程语言是都说的是 块作用域。 我学的假编程吗？

我和作者一样，学了一点点的CPP，非常高兴出现了Rust这门语言解决了此危机。
之前看写CPP的同事，写的服务端程序崩溃了，缺找不到原因，看的实在着急。
Rust应该解决了此问题吧。

**Comment by ZhangHanDong** [comment]
@Aaron009 可以查看本仓库issues里Pin起来的第三个issues就有讨论：https://github.com/ZhangHanDong/tao-of-rust-codes/issues/75

**Comment by Aaron009** [comment]
@ZhangHanDong 书中说用花括号创造词法作用域，词法作用域我是第一次看到，以前我学习其他编程语言是都说的是块作用域。

块作用域是不是就是词法作用域。

**Comment by ZhangHanDong** [comment]
@Aaron009 可以这么理解。
