### ISSUE TITLE
第44页的代码清单2-5注释错误

### ISSUE THREAD

**Issue by Cyberlin** [ZhangHanDong/tao-of-rust-codes#322]
# 页码与行数

- 第44页
- 代码清单2-5

---

# 文本或排版错误

> 暂无

---

# 代码注释错误

```rust
fn main() {
    let place1 = "hello";
    let place2 = "hello".to_string();
    let other = place1;
    println!("{:?}", other);
    let other = place2;
    println!("{:?}", other);//Err: other value used here after move
}
```
实际上运行没有报错
![image](https://user-images.githubusercontent.com/62041830/123913572-f30b2f00-d9b0-11eb-8f5b-3164ebe6f1c2.png)

### Rust版本

```
$  rustc -V
rustc 1.52.1 (9bc8c42bb 2021-05-09)

```

### 错误信息

```rust
代码注释错误
```

**Comment by ZhangHanDong** [comment]
多谢反馈，这个问题已经重复反馈了，也在后来的印刷版修复了。可以对照下已提交的issues。
