### ISSUE TITLE
13.2.2 子类型和型变问题

### ISSUE THREAD

**Issue by Kotodian** [ZhangHanDong/tao-of-rust-codes#332]
关于对代码清单13-17的分析中
1. 举的是一个'static的例子,但是这个代码跟用不用static也没什么关系,就算不用static也是有问题的。
2. 书里又说step1函数中的第一个参数val的生命周期是'a,val的生命周期不应该是比'a短的吗,后面说允许协变所以变成'static, val的引用生命周期应该是比‘static短的吧,它不能协变成'static吧。
3. 我还是不太能够根据你的分析得到一个结论

**Comment by ZhangHanDong** [comment]
@Kotodian ？？？
