### ISSUE TITLE
「第二章」关于#[no_std] "不使用标准库声明"的问题

### ISSUE THREAD

**Issue by pyclear** [ZhangHanDong/tao-of-rust-codes#34]
# 页码与行数

- 第14页
- 第3行

---

# 文本或排版错误

> 除非使用#[no_std]属性明确指明不需要标准库，应为#![no_std]

---

**Comment by ZhangHanDong** [comment]
@pyclear 感谢反馈 

`#[no_std]`具体来说是可以用的，可能这里让你产生困惑了，我修改下原文。

> 使用`#![no_std]`或`#[no_std]`属性
