### ISSUE TITLE
[第二章] 代码清单2-20 match表达式

### ISSUE THREAD

**Issue by lius-new** [ZhangHanDong/tao-of-rust-codes#340]
# 页码与行数

- 第24页
- 第5行

---

# 文本或排版错误

> 代码是否出错，是否存在`1...3`这样的语法

**Comment by ZhangHanDong** [comment]
这个语法之前是存在的，后来改为了 `..=`，这本书已经出版四年了，请关注第二版吧，覆盖2024 edition
