### ISSUE TITLE
「第三章」`3.4.3` 节代码清单 3-41 错误

### ISSUE THREAD

**Issue by yct21** [ZhangHanDong/tao-of-rust-codes#37]
# 页码与行数

- 75
- 第 39 行

---

# 代码错误

代码清单 3-41 的 29 行后缺少 `main` 函数声明

**Comment by ZhangHanDong** [comment]
@yct21 这不是错误。

代码清单3-41是对第2章代码清单2-53的重构，可以返回去看看，或者看随书源码。书上面是限于篇幅，省略了main。

**Comment by ZhangHanDong** [comment]
@yct21 这不是错误。

代码清单3-41是对第2章代码清单2-53的重构，可以返回去看看，或者看随书源码。书上面是限于篇幅，省略了main。

**Comment by ZhangHanDong** [comment]
@yct21 看这里

[随书源码在线代码示例](https://ruststudy.github.io/tao_of_rust_docs/tao_of_rust/ch03/abstract_type/fn.impl_trait.html)

**Comment by yct21** [comment]
好吧, 话说好像也没省几行代码, 看着怪怪的. 建议至少加一下省略号吧.

顺便书里的缩进好像和随书代码里不太一样.

```rust
use std::fmt::Debug;
    pub trait Fly {
          fn fly(&self) -> bool;
    }
```

**Comment by ZhangHanDong** [comment]
@yct21  刚发现，这个缩进排版有问题。

**Comment by ZhangHanDong** [comment]
@yct21 感谢反馈。已经提交给出版社。
