### ISSUE TITLE
「第五章」`5.4` 节 `所有权借用` 的文本错误

### ISSUE THREAD

**Issue by yct21** [ZhangHanDong/tao-of-rust-codes#38]
# 页码与行数

- 第 133 页
- 第 10 行

---

# 文本或排版错误

> `len` 方法中的 `&self` 实际上是 `self: &self` 的简写

此处应为 `self: &Self`

**Comment by ZhangHanDong** [comment]
@yct21 感谢反馈。

**Comment by yct21** [comment]
> @yct21 感谢反馈。
> 
> 这个在第六章也会介绍到。

第六章介绍到的那块 （190 页 17 行），

> `Self` 对应 `self: Self`

这里的简写应该是小写的 `self` 吧

**Comment by ZhangHanDong** [comment]
嗯，这个已经勘误了。
