### ISSUE TITLE
「第九章」文本语义不通顺

### ISSUE THREAD

**Issue by koushiro** [ZhangHanDong/tao-of-rust-codes#4]
# 页码与行数

- 第318页
- 最后一行

---

# 文本或排版错误

> 在代码清单 9-39 中,通过 From 为 Error 实现转换到 std::io::Error 和 std::num::ParseIntError

不知道是不是我理解有问题， 我觉得应该是 `通过为Error实现From，将std::io::Error和std::num::ParseIntError转换为Error`, 这样看起来更通顺。

看完了第九章的样章，张老师写得很好，书已经下单。

ps：也感谢张老师的Rust每日新闻频道，收获很多。

**Comment by ZhangHanDong** [comment]
@koushiro  感谢反馈，我回头对照一下再给你回复
