### ISSUE TITLE
「第三章」建议介绍一下 MIR 的使用方式

### ISSUE THREAD

**Issue by keroro520** [ZhangHanDong/tao-of-rust-codes#41]
我目前只看到第三章，不知道这个建议有没有在后面章节做了。

MIR 一定程度上表示了 “源代码在编译器眼中是什么样子的”。所以我为了查看 MIR，找了很久，最后才（只）知道可以通过 https://play.rust-lang.org 来查看。

我认为了解 MIR ，这种从编译器的视角去看代码的方式，能帮助我们更深刻地了解 Rust 的心智模型。所以建议书中介绍一下，怎么查看 MIR。

另外，在 P37 中介绍枚举体 “这样的枚举值本质上属于函数指针类型”。我第一次知道这个知识点时是有点震惊的，而如果能此时够贴上相应的 MIR，相信更能解释这个知识点。
如果在这个知识点下面，再继续普及一下 [constructors-as-functions](https://doc.rust-lang.org/1.5.0/book/enums.html#constructors-as-functions) ，就更好了。

**Comment by ZhangHanDong** [comment]
@keroro520  感谢建议。

MIR在第五章 5.8有详细介绍。另外，Constructor-as-functions，我并没有单独拿出来讲，而是融入到具体的示例中了。可以在看的时候发现。

期待你更多反馈。

**Comment by ZhangHanDong** [comment]
@keroro520  补充

书里的「函数指针类型」，是指「函数类型签名」。我的本意是指，它是一个函数指针。
考虑在第三次印刷中修正它。

**Comment by ZhangHanDong** [comment]
@keroro520  正好，另外一个issues里，我回答了MIR相关的一些内容，你可以看看。

[函数指针类型的一点建议 #42](https://github.com/ZhangHanDong/tao-of-rust-codes/issues/42)

**Comment by ZhangHanDong** [comment]
@keroro520 关于函数指针类型这个问题，也最好看看那个 [函数指针类型的一点建议 #42](https://github.com/ZhangHanDong/tao-of-rust-codes/issues/42)

**Comment by ZhangHanDong** [comment]
@keroro520 

「“这样的枚举值本质上属于函数指针类型”」

修订为：

「函数项类型（Function-Item Type），它可以通过显式地指定函数类型来转换为函数指针类型（Function-Pointer Type）。但如无必要，不要进行这样的显式转换，默认使用函数项类型性能更好。」
