### ISSUE TITLE
「第十一章」`11.2.7` 节 `内部可变性探究` 的文本错误

### ISSUE THREAD

**Issue by yct21** [ZhangHanDong/tao-of-rust-codes#49]
# 页码与行数

- 第 399 页
- 第 6 行

---

# 文本或排版错误

> 通过 `as` 将 `T` 类型中的不可变借用先转换为 `* counst T`

此处应为 `* const`

**Comment by ZhangHanDong** [comment]
@yct21  感谢感谢
