### ISSUE TITLE
「第十一章」`11.3.2` 节 `future 并发模式` 文本错误

### ISSUE THREAD

**Issue by yct21** [ZhangHanDong/tao-of-rust-codes#50]
# 页码与行数

- 第 420 页
- 第 11 行

---

# 文本或排版错误

> 分别为 `FutureObj` 和 `Arc<WeakHandle>` 类型

> 而 `WeakHandle` 则是用来唤醒任务的句柄

此处应为 `WakeHandle`

**Comment by ZhangHanDong** [comment]
@yct21 收到，感谢感谢，真细心。
