### ISSUE TITLE
「第二章」`2.4.5 CTFE 机制` 常量表达式的部分描述不准确

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#54]
# 页码与行数

- 第 20 页
- 2.4.5 小节 最后一段 第三句

---

# 文本或排版错误

> Rust 编译器目前可以支持的常量表达式有：……只包含**单行代码**的块表达式……

我觉得这里的描述可能不太准确，多行代码的块表达式也可以存在，只要每行代码在编译期均可确定求值即可。

**Comment by ZhangHanDong** [comment]
@eZioPan  感谢反馈。

Rust现在应该不支持多行的块表达式做为常量，最好自己代码尝试一下。

**Comment by eZioPan** [comment]
这是我测试的代码，可以编译成功的，我用的 `rustc` 是 `1.31.1` 的版本，不知道是不是版本的问题呢？
```rust
const V: usize = 5;

fn main() {
    let arr1: [u8; ctfe_f(V)] = [0, 1, 2, 3, 4, 5, 6, 7];
    println!("{:?}", arr1);
}

const fn ctfe_f(v: usize) -> usize {
    const A: usize = 1;
    const B: usize = A * 2;
    v + A + B
}
```

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈。

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈。

**Comment by ZhangHanDong** [comment]
可能需要补清楚说明，加个注释
