### ISSUE TITLE
「排版」书中一些英文单词的大小的建议

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#55]
# 页码与行数

- [x] 第 6 页

  > Rust 语言文档支持 **MarkDown** 格式

  写为 *Markdown* 比较好

- [x] 附录 A.1

  > **PlayGround** 的功能很丰富

  写为 *Playground* 与前后文统一

- [x] 附录 A.5.1

  > 很多编辑器都需要安装它（**Interllij** IDEA Rust

  应该为 *InterlliJ*  // 大写的字母 J

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈
