### ISSUE TITLE
[第四章] 关于结构体对齐规则

### ISSUE THREAD

**Issue by wucheng** [ZhangHanDong/tao-of-rust-codes#56]
# 页码与行数

- 第102页
- 图4-8即下面描述

struct结构体对齐的规则，结构体A的长度是8个字节，但是内存布局不应该是图中所示a后面补充了1个字节，因为如果是这样，b的开始地址也不是4字节对齐的。

最终struct A是8个字节，是因为编译器对结构体成员进行了地址重排，先后顺序是b, c, a
如输出的其实地址所示

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=83128ce39b5e1b3ca58e77035f1111c5
---

# 文本或排版错误

**Comment by wucheng** [comment]
116页，图4-11应该也是同样问题
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2984b495e92678a21a62f38bc53e41de

关于struct重排这个，搜了下rust文档有一些描述
https://doc.rust-lang.org/beta/nomicon/repr-rust.html

**Comment by ZhangHanDong** [comment]
@wucheng 感谢反馈。我看看先。

**Comment by HoNooD** [comment]
> 116页，图4-11应该也是同样问题
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2984b495e92678a21a62f38bc53e41de
> 
> 关于struct重排这个，搜了下rust文档有一些描述
> https://doc.rust-lang.org/beta/nomicon/repr-rust.html

读 102 页的时候特别困惑。感谢你对这个问题的分析，并给出[相关文档](https://doc.rust-lang.org/nomicon/repr-rust.html)。

**Comment by yim7** [comment]
已经有读者反映就不需要重开 issue 了~
看这节时没理解找文档看了下，作者对于内存布局解释确实有错误，先不说 rust 的内存布局。书中 102 页倒数第2行“那么对于成员 a 来说，它的对齐值为 MIN(4, 1)， 即 1， 所以 a 需要补齐一个字节的空间”
成员 a 的 大小和对齐值都是1，所以它可以存在任何地址，是不需要补齐的。到下一个字段 b ，它需要偏移地址是 4 的倍数 ，所以需要填充 3 个字节。到字段 c ， 因为加上 b 的大小的偏移，这时候的偏移已经是 4 的倍数了，所以 c 也不需要补齐。但是 struct 的对齐值等于其字段对齐值的最大值，也就是 4 ，所以要在 c 后面 补齐  2 个字节，使 struct 大小是 4 的倍数。这种布局有 5 个字节大小的内存浪费，如果我们调整字段顺序，只需要在最后补齐1个字节
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1e11e47677797bbf1bc1840357fd1872
```rust
#[repr(C)]
struct A {
    b: u32,
    c: u16,
    a: u8,
}
fn main() {
    println!("{:?}", std::mem::size_of::<A>()); // 8
    let v = A { a: 1, b: 2, c: 3 };
    println!("&v {:p}", &v);
    println!("&v.b {:p}", &v.b);
    println!("&v.c {:p}", &v.c);
    println!("&v.a {:p}", &v.a);
}

```

以上说的是 repr(c) 的布局方式，rust 默认布局 struct 字段顺序是不确定的，编译器会进行优化调整字段顺序，以避免内存浪费的情况

参考
https://doc.rust-lang.org/reference/type-layout.html
https://doc.rust-lang.org/nomicon/repr-rust.html

**Comment by ZhangHanDong** [comment]
@yim7 感谢反馈。这部分还没抽出时间来确认，这周内看看。后续贴出更正内容。

**Comment by ZhangHanDong** [comment]
@wucheng @yim7

今天看了下这个问题，两位描述的是正确的。通过查看生成的LLVM IR可以直接看到补齐。

```rust
struct A {
    a: u8,
    b: u32,
    c: u16,
}
```

LLVM IR : 

```rust
%A = type { [0 x i32], i32, [0 x i16], i16, [0 x i8], i8, [1 x i8] }
```

看得出来是重排了。给u8类型的a，分配了一个字节。

@wucheng  nomicon的文档我是看过，估计是我自己后来忘记修改这块内容了，写书写到后面，有点麻木。再次感谢你们的反馈。

**Comment by ZhangHanDong** [comment]
图4-8 修改为：

![image](https://user-images.githubusercontent.com/27893/52528769-e5da4080-2d20-11e9-90fb-89e3518295ce.png)

**Comment by ZhangHanDong** [comment]
@yim7 

你这个例子应该修改为：

```rust

#![allow(unused)]
#[repr(C)]
struct A {
    a: u8,
    b: u32,
    c: u16,
    
}
fn main() {
    println!("{:?}", std::mem::size_of::<A>()); // 12
    let v = A { a: 1, b: 2, c: 3 };
}
```

才能看出没有重排的效果。是浪费了5个字节。

**Comment by ZhangHanDong** [comment]
图4-11修改：

![image](https://user-images.githubusercontent.com/27893/52529009-64d17800-2d25-11e9-9b98-ecffaaa76674.png)

**Comment by ZhangHanDong** [comment]
图4-12修改为：

![image](https://user-images.githubusercontent.com/27893/52529196-cfd07e00-2d28-11e9-9590-dc3adfded26d.png)
