### ISSUE TITLE
[第四章]联合体的说明很难找到（讲解联合体的索引应该是第13章，而不是第7章）

### ISSUE THREAD

**Issue by gabin22** [ZhangHanDong/tao-of-rust-codes#58]
# 页码与行数

- 第103页
- 第3行

---

# 理解困难
> 没学过联合体，无法理解联合体的成员为什么能共用内存，到32页2.7节找联合体的说明，又被指引到第七章找，但是很难找到。如果读者不明白联合体的意义，就会强以结构体去理解，对其内存对齐方式感到莫名其妙。而第四章涉及的概念要到第七章才能找到说明，也不太合适。

---

**Comment by ZhangHanDong** [comment]
@gabin22 感谢反馈。

第7章那个应该是忘记改了。。。本来内容在第7章，后来我挪到第13章了，前面的索引忘记修改了。这是个错误。
第四章的重点是内存布局，先理解内存布局，结构体和union的不同。在第13章，你会知道它对内存安全有什么影响。
Rust引入union也主要是为了和C打交道，所以，你在看到unsafe那部分章节去了解union，更好。不要着急。
