### ISSUE TITLE
「第二章」2.3.3，2.4.6 相关代码有误

### ISSUE THREAD

**Issue by lanzhiheng** [ZhangHanDong/tao-of-rust-codes#60]
代码清单2-5
# 页码与行数

- 16

# 代码错误

```rust
fn main(){
    let place1 = "hello";
    let place2 = "hello".to_string();
    let other = place1;  
    println!("{:?}", other);
    let other = place2;   
    println!("{:?}", other);  // Err: xxxx
}
ownership();
```

书中的第二章所有权方面的代码是像上面这样的，编译可以通过的，按照原文的注释还有描述，编译不应该通过才对，这里会误导读者。我看你[源码](https://ruststudy.github.io/tao_of_rust_docs/tao_of_rust/ch02/binding/fn.ownership.html)这里是改过来了，是不是书本没有改过来？

**Comment by lanzhiheng** [comment]
况且如果像你源码那样改

```
fn main(){
    let place1 = "hello";
    let place2 = "hello".to_string();
    let other = place1;  
    println!("{:?}", place1);
    let other = place2;   
    println!("{:?}", place2);  // Err: xxxx
}
```

`place1`其实是可以打印的，只有下面`place2`的地方报错了，也就是说前者的所有权没有转移。应该是跟附值的时候有没有加上`to_string`有关，这里会涉及两个概念了，而且对为什么`place1` 的地址没有转移没有说清楚。如果这一个单元是专门讲所有权的化建议简化一下例子

```
pub fn ownership(){
    let place1 = "hello".to_string();
    let other = place1;  
    println!("{:?}", place1); // Err xxxx
}
```

专注于一个知识点。

**Comment by Cycade** [comment]
书上 print 的还是 other，实际应该是 place1 和 place2，确实会引起不少误导，希望能修改一下

**Comment by lanzhiheng** [comment]
@ZhangHanDong  另外临时变量的这几条语句是跑不过编译的

``` rs
  let mut _0: &i32;
  let mut _1: i32;
  _1 = const 42i32;
  _0 = &_1
```

不确定是不是版本问题

```
>  rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)
```

报了这个错

![image](https://user-images.githubusercontent.com/8858472/51024250-fed9bf80-15c3-11e9-8f67-80b41ae6887f.png)

应该下面这条语句才是你想要表达的吧?

```
let mut _0: &i32;
const _1: i32 = 42i32;
_0 = &_1;
println!("{:p}", _0);
```

**Comment by ZhangHanDong** [comment]
@lanzhiheng 感谢反馈。 那个错误已经第二次印刷修改。另外，那个创建临时变量示例是为了说明，可以看作伪代码示意。代码下面文字已经说了：仅用于演示。

**Comment by lanzhiheng** [comment]
@ZhangHanDong OK，我觉得伪代码可能用区分度更高的别的语言来说明可能会更好些，不然可能很多人都会没注意到下面一段话就直接拿代码去运行了。

**Comment by ZhangHanDong** [comment]
@lanzhiheng 嗯。这个地方我会考虑下。多谢反馈。

**Comment by lanzhiheng** [comment]
@ZhangHanDong 刚发现另外一处错误 2.4.6节，代码示例 2-14 闭包作为参数的情况

里面定义了一个`closure_math`调用的确是`math`，编译器会报错。另外就是下面的文字描述用的都是`math`方法，这个需要修正一下。我就不另外建issue了，这个issue还开着的话。

**Comment by ZhangHanDong** [comment]
@lanzhiheng 嗯，这个也有人提过了。第二次印刷已经修正，不过下面的说明文字还是closure_math，给忘记了。。。等第三次印刷修正吧。

感谢反馈。
