### ISSUE TITLE
「第二章」`2.5.2 循环表达式` 有关 “CTFE 机制未完善导致的问题”的建议

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#63]
# 页码与行数

- 第 23 页
- 最后 1 段

---

# 文本或排版错误

> 此时编译器只知道 while true 循环返回的是单元值，而函数返回的是 i32，其他情况一概不知。

我觉得这样表述比较好：

> 此时编译器只能假定 while 循环返回的是单元值，而函数需要的返回值类型为 i32，于是就产生了冲突。

因为无论 while 循环的条件是什么，它的返回只目前都只能被假定为单元值，与循环条件是否为真无关

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢反馈。我斟酌一下。

**Comment by ZhangHanDong** [comment]
@eZioPan 

和while true是一样的，我怎么理解的，都在书里。

代码清单2-18下方：

> 这是因为Rust 编译器在对while 循环做流分析（Flow Sensitive）的时候，不会检查循环
条件，编译器会认为while 循环条件可真可假，所以循环体里的表达式也会被忽略，此时编
译器只知道while true 循环返回的是单元值，而函数返回的是i32，其他情况一概不知。

换成if true道理是一样的。

**Comment by eZioPan** [comment]
根据 `if` 表达式返回的错误 `expected type (), found type i32`，这里我觉得，编译器应该是已经判断出来 `if` 表达式返回值的类型为 `i32` 了，既然是已经知道返回值的类型，且刚好就是函数需要返回的值类型，那直接返回它不就可以了么？为什么还要提示 `expected type ()` 呢？

**Comment by eZioPan** [comment]
明白啦，谢谢！
