### ISSUE TITLE
[第六章] 6.2.3 闭包所有权疑似印刷问题

### ISSUE THREAD

**Issue by flame4** [ZhangHanDong/tao-of-rust-codes#64]
# 页码与行数

- 第180页
- 第9行

---

# 文本或排版错误

代码清单6-32, 第9行代码, 'c;' 应该是 'c();' ?

**Comment by ZhangHanDong** [comment]
@flame4 是的。排版错了。以随书源码为准。

[https://ruststudy.github.io/tao_of_rust_docs/tao_of_rust/ch06/closures/fn.closure_gen_type.html](https://ruststudy.github.io/tao_of_rust_docs/tao_of_rust/ch06/closures/fn.closure_gen_type.html)
