### ISSUE TITLE
「第十三章」WASM内存泄漏相关描述需要修改

### ISSUE THREAD

**Issue by ZhangHanDong** [ZhangHanDong/tao-of-rust-codes#65]
# 页码与行数

- 第533页

介绍WebAssembly时

> 没必要担心内存泄漏

删掉这句话，还是存在一定内存泄漏风险，需要开发者考虑好

**Comment by ZhangHanDong** [comment]
代码清单13-85 下方描述： 「它实际上是一个指针」，需要修改「它」的指代名称。

**Comment by kvinwang** [comment]
> 删掉这句话，还是存在一定内存泄漏风险，需要开发者考虑好

其实并不仅仅"还是存在一定内存泄漏风险"，而是在内存泄露方面，与编译到Native是等效的，wasm并没有任何优势。js的善后行为就相当于native程序运行完后操作系统的善后行为。
