### ISSUE TITLE
「第二章」vec 这个概念还没有介绍就先使用了

### ISSUE THREAD

**Issue by eZioPan** [ZhangHanDong/tao-of-rust-codes#68]
# 页码与行数

- 第 25 页
- 代码清单 2-22：使用 match 表达式

- 第 30 页
-  2.6.6 节最后一段

---

# 文本或排版错误

> let mut v = vec![1,2,3,4,5];

> 对使用 vec! 宏定义的动态数组，也可以通过引用操作符来得到一个切片

书中因该是 第 38 页 `2.8.1 节` 中才解释了 `向量` 的概念。

代码清单 2-22 中的内容还比较好猜测 vec! 的含义，但 2.6.4 节中刚提了已经实现的`固定长度数组`，和将要实现的 `可变长数组（VLA）`，2.6.6 节最后又提及了 `vec! 宏` 定义的 `动态数组` 的 `切片`，这里是不是太早提及了 `vec` 和 `vec!` 的概念，同时和前面的数组的概念又比较相似，容易产生混淆呢？

**Comment by ZhangHanDong** [comment]
@eZioPan  这个应该没关系的。暂时存疑嘛，读者又不是只看第二章。而且第二章，是一个语法的整体介绍，目的是让大家把语法整体性过一遍，先存在一个印象，后面才方便展开讲解。不可能把所有东西都堆在第二章。

目前根据反馈，大家看着还行。
