### ISSUE TITLE
「第二章」值表达式出现在位置上下文时的疑问

### ISSUE THREAD

**Issue by fortunewang** [ZhangHanDong/tao-of-rust-codes#72]
# 页码与行数

- 2.3.1节 第15页 代码清单2-3上方
- 2.3.3节 第17行 代码清单2-7上方

---

# 疑问

2.3.1节中说到：

> 值表达式不能出现在位置上下文中，如代码清单 2-3 所示。

而2.3.3节对代码的释义中说：

> 对于字面量 42 来说，其本身属于值表达式。通过引用操作符，相当于值表达式在位置上下文中进行求值，所以编译器会为 &42 创建一个临时值，如代码清单 2-7 所示。

我认为这两处的说法是存在矛盾的。当值表达式出现在位置上下文中时，到底是会产生编译期错误呢，还是会创建临时值呢？

我试图从 Rust 官方文档中寻找答案。

我暂时还没有从官方文档中找到「值表达式不能出现在位置上下文中」的说明，但却找到了关于 2.3.3 节中[创建临时值的说明](https://doc.rust-lang.org/reference/expressions.html#temporary-lifetimes)：

> When using a value expression in most place expression contexts, a temporary unnamed memory location is created initialized to that value and the expression evaluates to that location instead, except if promoted to `'static`.

应证了 2.3.3 节中的说法是正确的。

而且，[官方文档同一章](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions)还有这样的话：

> Expressions are divided into two main categories: place expressions and value expressions. Likewise within each expression, sub-expressions may occur in either place context or value context.

那么，是否「值表达式不能出现在位置上下文中」这一说法存在问题？
如果这一说法不正确，代码清单 2-3 中编译错误的原因又是什么呢？是不是与上下文无关，而是具体到`let`语句中对等号左边的pattern的要求呢？

---

# 页码与行数

- 546页 A.2.2节 第一行

---

# 文本或排版错误

中国科学技术大学（USTC）遗漏「大学」两字。

**Comment by ZhangHanDong** [comment]
@fortunewang 代码清单 2-3示例就是「值表达式」出现在位置上下文中的情况，它会报错。

「从语义角度来说，位置表达式代表了持久性数据，值表达式代表了临时数据」。

`let  a = 1`

这条赋值语句，实际表达的意思是什么呢？ 往内存中存储一个数据`1`。存储这个数据的地址由变量`a`持有。

等号左边就是位置上下文，代表内存位置，右边代表值上下文，代表数据。 

值表达式不能出现在位置上下文，表示，你不能写成 `let 1 = 2`。 因为这个`1`，本身是个临时数据，它会被存储到某地，但是它存在什么位置，你不知道，你怎么用它呢？

代码清单2-3也一样，函数`let temp() = 2`，函数temp返回值是一个数字`1`，它是不能作为变量的。

理解这个概念，主要是理解Rust中把变量称为“绑定”的意义。是把一个值，绑定给它的内存。

看书不要想太多。结合书中章节的上下文去理解，里面的知识点本来都是串联的，你不要单独拎出来胡思乱想。

**Comment by fortunewang** [comment]
感谢解答。

`1 = 2`这样是错误的。因为`1`是数据，不代表内存地址，赋值正是需要内存地址的场合，因此这是完全错误的用法。

这是您从**语义**方面做出的解答。我已理解。

我的问题是因为我死扣**语法**产生的，我查阅文档后也已得到了解决。

----------------------------

**语法**方面，我依然保留自己的观点，也即没有「值表达式不能出现在位置上下文中」这一说法。

我的理解是，在大多数情况下，值表达式可以出现在位置上下文中，编译器会为此创建一个临时值。

一个例外是，之前引用过的，值表达式为`'static`的情况。

而`1 = 2`这种，赋值表达式是另一个[例外](https://doc.rust-lang.org/reference/expressions/operator-expr.html#assignment-expressions)：

> The left-hand operand must be a place expression: using a value expression results in a compiler error, rather than promoting it to a temporary.

---------------------------

```
let 1 = 2;
let temp() = 2;
```

这两种**语法**错误似乎就和表达式上下文关系不大了。
由于let语句左侧是一个pattern，这两种错误应当是和pattern有关系的：

* `let 1 = 2`所产生的编译错误是，左侧的`1`是一个refutable pattern。
* `let temp() = 2`所产生的编译错误是，`temp`不是tuple struct或variant，所以`temp()`不是一个合法的pattern。

**Comment by ZhangHanDong** [comment]
@fortunewang 感谢回复。晚点再和你交流。

**Comment by ZhangHanDong** [comment]
@fortunewang 暂时关闭此问题。

无论什么原因，「值表达式不能出现在位置上下文」属于一种客观的结果。  除非你给出一种合法的反例。

至于为什么，后续抽出时间可以再研究交流。
