### ISSUE TITLE
「建议」添加章节的label

### ISSUE THREAD

**Issue by YuiFn** [ZhangHanDong/tao-of-rust-codes#73]
为现有的issues添加章节的label，这样一来方便后来的人通过label快速定位这些章节哪里有勘误，也方便作者后期做勘误对照。现在智能通过搜索来做

**Comment by ZhangHanDong** [comment]
@YuiFn 好主意

**Comment by ZhangHanDong** [comment]
@YuiFn 已经增加章节label
