### ISSUE TITLE
[第四章] 建议去除"虚拟地址空间"的引入

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#74]
# 页码与行数

-  第96页
第4章中，一开始花了一定的篇幅介绍“虚拟地址空间”的概念，并且在后文中堆与栈的知识点都在引用“虚拟地址空间”导致一些概念错误。

例如：
97页
> 不管什么算法，分配的都是虚拟地址空间。所以当堆空间被释放时并不代表物理空间也马上被释放。

这里有两个问题：
- 暗指这些内存分配算法和虚拟地址空间有什么关联，实际并没有什么关联，这些内存分配算法同样也能用在实地址模式工作的程序中，并没有区别
- “所以...”, 这里前后两句话并没有因果关系，内存释放后被归还到分配器的池子中，这是分配器的具体实现策略，和“虚地址空间没”有关系，也不是所有的分配器都会这么实现。

103页
> 采用虚拟内存空间在栈和堆上分配内存，这是诸多编程语言通用的内存管理基石，Rust当然也不例外。

采用虚地址与否，并不是编程语言决定的，也不会影响到编程语言的内存管理，而是程序运行环境的行为，编程语言并不知晓。编程语言的内存管理对虚地址和实地址等效。

实际上本章想要介绍的堆、栈内存管理原理无需引入“虚拟地址空间”的概念，它们是独立工作的东西。堆栈在虚地址还是实地址上工作方式是完全一样的，引入多余的概念增加理解成本的同时为下文添乱。

**Comment by ZhangHanDong** [comment]
@kvinwang 感谢反馈。 这些我会斟酌考虑。

**Comment by ZhangHanDong** [comment]
@kvinwang 我大概明白你的意思。像在一些嵌入式系统里，不存在虚拟内存和物理内存之间的映射关系，也照样有栈和堆之分。 这点我会增加批注来说明。

但是在写书的时候，我是考虑到有些人（初学者）并没有这种前置知识，所以增加了这样一段通用概念。以「有虚拟内存空间」的操作系统为例（有些内容必须有铺垫的素材才能说出来），来说明堆和栈的区别。当然这部分内容应该还存在更多的精简空间，我会再精简它。 

你说出的97页和103也的描述，确实可能会引起歧义，这些我会进一步修正描述。

**Comment by kvinwang** [comment]
> 以「有虚拟内存空间」的操作系统为例（有些内容必须有铺垫的素材才能说出来），来说明堆和栈的区别

这个需求只有在画内存布局图的时候用到，给图标注是以某某平台某某架构为例，一句话带过就行了。有需要深入了解的读者自行查阅相关书籍。后文都不需要“虚拟内存空间”这个概念。

**Comment by ZhangHanDong** [comment]
@kvinwang

「不管什么算法，分配的都是虚拟地址空间。所以当堆空间被释放时并不代表物理空间也马上被释放。」

修改为：

「在使用虚拟地址空间的系统中，当堆空间被释放时，并不代表指物理空间也马上被释放」

书的内容只限定在「使用虚拟内存地址空间」的系统中，比如Linux、macOSX等。另外，我加这些内容，是为了照顾新手，让新手看着顺畅，而不需要跳出本书再去翻找另外的资料查阅。是为了阅读体验考虑。

「采用虚拟内存空间在栈和堆上分配内存，这是诸多编程语言通用的内存管理基石，Rust当然也不例外。」

这句话我并没有说是编程语言决定的呀，前面铺垫了那么多，说的就是操作系统呀。要结合上下文理解。

**Comment by kvinwang** [comment]
> 修改为：
> 
> > 「在使用虚拟地址空间的系统中，当堆空间被释放时，并不代表指物理空间也马上被释放」

正确的说法是：「常见的堆内存分配器中，当内存被释放时，并不会马上归还给系统」（注意这里的“系统”并不一定指操作系统，而是一个泛指的概念）
 - 因为并不是所有内存分配器都会这么实现，所以要加个“常见”
 - 因为这些内存分配器不必工作于虚拟地址空间上，没必要加个前提限制在这儿，干扰视线。
 - "`并不代表指物理空间也马上被释放`",  即使是在虚拟地址上工作，这句话也没必要强调物理空间，因为实际是虚拟地址没有马上被释放，当然物理空间也就不会被释放。加上物理二字后，给人的感觉就好像虚拟地址已经被释放，只是物理内存还没释放。


> 另外，我加这些内容，是为了照顾新手，让新手看着顺畅，而不需要跳出本书再去翻找另外的资料查阅。

并不感觉加上这个概念会使新手阅读更顺畅，而是加重了理解的负担。这些内容对理解堆/栈本身没有帮助，所以也不需要去查阅资料，只有对“虚拟地址空间”这个概念本身有兴趣的，才需要去查另外资料。



> 另外，栈和堆的概念对于理解Rust很重要，必须得加上，这是不可跳过的

这是自然，我并没有说要把堆/栈的内容去掉。


> 否则很多概念是说不明白的

不存在说不明白，只有画图的时候（因为必须要画一个具体的布局出来, 就必须以某种环境实现为例来画）需要标注一下是"以某某环境/平台的实现为例来画的", 因为不标注的话，读者可能误以为都是这么实现的。


> > 「采用虚拟内存空间在栈和堆上分配内存，这是诸多编程语言通用的内存管理基石，Rust当然也不例外。」
> 
> 这句话我并没有说是编程语言决定的呀，前面铺垫了那么多，说的就是操作系统呀，要结合上下文理解

前面再多铺垫也不影响这句话本身表达的意思有问题：`采用虚拟内存空间...，是...内存管理的基石`,  ”虚拟地址空间“这个技术跟语言里面的内存管理没有关系，不能说它是后者的”基石“。

---
最后，举个简单点的例子：DOS操作系统可以选择配置成工作在”实地址模式“或”虚地址模式“， 但已经编译好的命令，在两种模式都能运行，这些命令并不会感觉到两种地址模式对自己内部的内存管理有什么影响。

**Comment by ZhangHanDong** [comment]
@kvinwang  感谢回复。基本认同。

但是「需要标注一下是"以某某环境/平台的实现为例来画的"」，我是有标注的呀，在批注里。32位linux X86模型。

**Comment by kvinwang** [comment]
> 但是「需要标注一下是"以某某环境/平台的实现为例来画的"」，我是有标注的呀，在批注里。32位linux X86模型。

我的意思不是说书上漏了标注，意思是只有这里需要标注(标注的时候可能需要提到(其实不提应该也没有太大影响)”虚拟地址空间“这个词), 其它地方都不需要这个词。
