### ISSUE TITLE
附录A:Rust开发指南

### ISSUE THREAD

**Issue by as981242002** [ZhangHanDong/tao-of-rust-codes#79]
- 第546页
- 第9行

---
通过rustup default命令指定一个默认的rustc版本: 
    rustc default nightly (此处应该为 rustup default nightly)
或者
    rustc drfault nightly-2018-05-12(此处应该为 rustup default nightly-2018-05-12)

**Comment by ZhangHanDong** [comment]
@as981242002  嗯？ 怎么关了

**Comment by as981242002** [comment]
我以为你直接改了-_-|||

**Comment by as981242002** [comment]
@ZhangHanDong  我以为你直接改了-_-|||
