### ISSUE TITLE
「第一章」考虑修改「Rust是跨平台语言，一次编译，到处运行」这个说法

### ISSUE THREAD

**Issue by ZhangHanDong** [ZhangHanDong/tao-of-rust-codes#8]
# 页码与行数

- 第一章
- 第10页
- 第3行

原文：

> 在进一步学习之前，我们有必要了解一下Rust 代码是如何执行的。Rust 是跨平台语言，
一次编译，到处运行，这得益于LLVM。Rust 编译器是一个LLVM 编译前端，它将代码编译
为LLVM IR，然后经过LLVM 编译为相应的平台目标。

 说的好像Java一样。。重新考虑一下描述

**Comment by ZhangHanDong** [comment]
考虑改为：

> 得益于 LLVM 的优秀兼容性， Rust 程序，只需编写一次，就能够有效的跨平台编译执行，大多数时候用户无需考虑平台特定语义的问题。

**Comment by ZhangHanDong** [comment]
进一步修改：

> Rust程序只需要编写一次，就能有效地跨不同的平台编译执行，大多数时候用户无需考虑各个平台的特定问题，这完全得益于LLVM的优秀兼容性。

**Comment by ZhangHanDong** [comment]
@mzji 嗯，再考虑考虑

**Comment by mzji** [comment]
> Rust 从诞生伊始，就考虑到了平台移植性问题，并为此做了诸多努力：LLVM 作为底层的代码生成框架，具有良好的移植性；标准库 std 在设计时也注重兼容多平台语义；编译器 rustc 在实现中尽可能弭平不同平台间的微小差异；等等等等。以上这些举措，都是为了让程序员能够更加轻松的编写跨平台可运行的代码；大多数时候，用户无需考虑各个平台的特有性质，而当用户需要处理跨平台兼容性问题的时候，rust 也提供了一些辅助的机制，以利于将不同平台的兼容问题包容在单个 crate 中解决。

**Comment by ZhangHanDong** [comment]
@mzji 

整段文字将修改为：

> Rust从诞生伊始，就考虑到了平台移植性问题。通常编译阶段被分为前端和后端两部分，Rust作为编译语言，也是这样划分的。Rust编译器是一个编译前端，它的工作是对代码进行词法分析、语法分析、类型检查、生成中间代码、进行独立于目标机器的优化等工作。使用LLVM作为编译器后端代码生成框架，则可以利用LLVM兼容多个目标机器的特性，实现跨平台编译和优化等工作。所以，在用户使用Rust时，大多数的时候，无需考虑各个目标机器平台的特有性质，基本上可以做到一次编写，到处运行。而当用户在需要处理跨平台兼容性问题的时候，Rust也以第三方crate的形式，提供了诸多辅助。
