### ISSUE TITLE
[第六章] `6.2.4节`印刷错误反馈

### ISSUE THREAD

**Issue by flame4** [ZhangHanDong/tao-of-rust-codes#80]
# 页码与行数

- 第190页
- 第26行

---

# 文本或排版错误
“其实之前trait中的self ..., 完整形式如下所示.”
具体说明的第一行, Self 应该为 self. 有一定误导性, 特此提示一下.

**Comment by ZhangHanDong** [comment]
@flame4 感谢反馈
