### ISSUE TITLE
「第十三章」为Ruby写扩展中GC处理技巧在批注中添加相关issues链接

### ISSUE THREAD

**Issue by ZhangHanDong** [ZhangHanDong/tao-of-rust-codes#84]
# 页码与行数

- 第529页
- Ruby小节的最后一段

---

将此issues添加到批注：[danielpclark/rutie/issues/21](https://github.com/danielpclark/rutie/issues/21)

此issues汇总了相关问题的链接

**Comment by kvinwang** [comment]
其实issue提到的问题并不是书中描述的问题。

@danielpclark 遇到的问题其实原理是这样的：

使用vec的时候，数据还没来得及返回给ruby 就被gc回收了，导致了段错误。

因为Ruby的GC是基于栈扫描根节点的，vec里面的东西不能以栈为根扫描到，GC就会认为没人用这些对象了，函数还没返回就有概率被gc回收掉。

放到栈上就能被Ruby的GC扫描到，就安全了。
