### ISSUE TITLE
第四章 105页 “空数组或向量可以初始化变量“ 这一段最后

### ISSUE THREAD

**Issue by codergege** [ZhangHanDong/tao-of-rust-codes#88]
# 页码与行数

- 第105页
- 空数组或向量可以初始化变量 这一小节最后一句

---

# 文本或排版错误

> 空数组或向量可以用来初始化变量，但目前展示无法用于初始化常量或静态变量

经过测试, Rust 2018 stable 版本中, 空数组可以用来初始化常量和静态变量了. 向量暂时不行.
```rust
pub fn main() {
    const BB: [i32; 0] = [];
    static CC: [i32; 0] = [];
}
```

---

### Rust版本

```
$ rustc -V
rustc 1.31.1 (b6c32da9b 2018-12-18)
```

**Comment by ZhangHanDong** [comment]
@codergege 感谢反馈，我抽空尝试一下
