### ISSUE TITLE
「第二章」代码清单2-24表达需要改进

### ISSUE THREAD

**Issue by bonfy** [ZhangHanDong/tao-of-rust-codes#89]
# 页码与行数

- 第26页
- 2-24 代码

---

# 代码错误

```rust
pub fn bool_type() {
    let x = true;
    let y: bool = false;
    let x = 5;
    if x > 1 { println!( "x is bigger than 1")};
    assert_eq!(x as i32, 1); // 是错误的 这个时候 x=5
    assert_eq!(y as i32, 0);
}
```
这个运行 断言`assert_eq!(x as i32, 1);`是错误的 这个时候 x=5

如果想表达 bool 的 true as i32 是1 的话，建议将断言移到  `let x=true` 之后

或者 第5行 和 第6行的 x 改为 新的变量 z 来说明 比较操作能产生 bool 类型

**Comment by ZhangHanDong** [comment]
@bonfy 感谢反馈。
