### ISSUE TITLE
[第八章] 272页， "未初始化内存"描述错误

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#90]
# 页码与行数

- 第272页

> 如果在整个函数中都未为其填充元素，则Rust编译器会认定它为未初始化内存，编译报错。

原因应改为“则编译器无法推断其类型，编译报错”

**Comment by ZhangHanDong** [comment]
@kvinwang
 感谢反馈。我抽空再确认一下。
