### ISSUE TITLE
[第十三章] 介绍Rust和其它语言交互时，建议增加论述和其它GC交互时的安全问题

### ISSUE THREAD

**Issue by kvinwang** [ZhangHanDong/tao-of-rust-codes#93]
正如[这里](https://github.com/danielpclark/rutie/issues/21)提到的，目前，Ruby的几个Rust绑定框架都存在GC引入的内存安全问题。之前rutie作者认为这是一个用户使用不当导致的问题，关闭了该issue。
实际上，在Rust的世界里，用户使用纯safe rust出现unsound， 都不应该是用户的责任， 应该归为rutie框架的bug。我对该问题进行补充之后，rutie作者已经开始寻找解决办法。dsander想通过GC mark或临时禁用GC来解决问题，但我认为这些方法都是unsound的，会使问题变得更复杂难查。（个人认为不是很好解决，可能大部分API需要重构）。

书中可以进一步论述一下，基于扫描栈上根节点进行mark的GC会存在该问题，像Python这种基于引用计数进行mark的GC则不存在该问题。

另外，在Rust中定义Ruby对象的析构(release)函数这种模式(书中也有介绍)，也存在隐蔽的安全问题，这里就不展开了。

**Comment by ZhangHanDong** [comment]
@kvinwang 感谢建议。我也正有此意，后续整理出来内容，再进行交流。

**Comment by motecshine** [comment]
引用计数 应该也要处理头疼的循环引用问题....

**Comment by kvinwang** [comment]
> 引用计数 应该也要处理头疼的循环引用问题

Python 的GC正是为了处理循环引用问题
