### ISSUE TITLE
[第八章]256页，“remove的参数为该字符的起始索引位置，这里需要注意，remove也按字节处理字符串的”

### ISSUE THREAD

**Issue by coderPonyGao** [ZhangHanDong/tao-of-rust-codes#94]
```
fn main() {
    let mut s1 = String::from("h1是123");
    println!("{}" ,s1.remove(2));//是
    println!("{}",s1);//h1123
}
```
书中写到remove也是按字节处理的字符串的，如果给的索引位置不是合法的字符边界，那么线程就会崩溃。 我在练习时发布 removie的参数是字符的索引位。

**Comment by ZhangHanDong** [comment]
@yy-gaoxu

感谢反馈

**Comment by eZioPan** [comment]
这里应该是没有错的，根据文档 [std::string::String.remove](https://doc.rust-lang.org/std/string/struct.String.html#method.remove) 中描述的：

> Removes a char from this String at a **byte position** and returns it.

> Panics if idx is larger than or equal to the String's length, or if it does not lie on a **char boundary**.

的确是按照字节位置索引的，也的确是在 `非 char boundary` 位置 panic。

@coderPonyGao 的代码中的 `索引 2` 就是指的 `是` 这个 char 的索引，String 的索引指的是每个 char **起始字节** 所在的字节索引

```rust
fn main() {
    let s1 = String::from("h1中文123");
    for i in 0..s1.len() {
        println!("index: {} content: {}", i, s1.clone().remove(i));
    }
}
```

返回内容：

```
index: 0 content: h
index: 1 content: 1
index: 2 content: 中
thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside '中' (bytes 2..5) of `h1中文123`', src\libcore\str\mod.rs:2109:5
```

**Comment by ZhangHanDong** [comment]
@eZioPan 感谢回复。

@coderPonyGao  eZioPan说的没错。

你示例中给你索引位，恰好是合法的，所以正常。 

```rust
pub fn remove(&mut self, idx: usize) -> char {
        let ch = match self[idx..].chars().next() {
            Some(ch) => ch,
            None => panic!("cannot remove a char from the end of a string"),
        };

        let next = idx + ch.len_utf8();
        let len = self.len();
        unsafe {
            ptr::copy(self.vec.as_ptr().add(next),
                      self.vec.as_mut_ptr().add(idx),
                      len - next);
            self.vec.set_len(len - (next - idx));
        }
        ch
    }
```

看一下remove函数的源码就知道了。这个方法会根据你传入的索引去判断字符的合法性。如果你索引位传的不合法，chars方法就会panic。 所以我说，你用remove的时候要注意，按字节计算。你按字节计算好合法的索引位，就不会panic。

**Comment by coderPonyGao** [comment]
@ZhangHanDong
