### ISSUE TITLE
【第四章】不管复合类型是否实现了Drop，它包含的成员都会递归调用 drop

### ISSUE THREAD

**Issue by yim7** [ZhangHanDong/tao-of-rust-codes#95]
# 页码与行数

- 第109页
- 倒数第6行

---

# 文本或排版错误

>“如果复合结构本身实现了 Drop，则会调用它自己的析构函数；否则，会调用其成员的析构函数”

这里应该是 **然后** 会调用其成员的析构函数，如果只调用它自己的析构函数，当它的成员是在堆上分配内存时就会发生内存泄露了
---

# 页码与行数

- 第105页
- 代码清单 4-6 第 6 行

---

# 文本或排版错误

>break 会将 x 的值返回

实际上代码中 break 返回的是 单元类型。这段代码的解释是不是应该在斟酌一下，我试着把break移出 if 表达式，就会提示use of possibly uninitialized variable: `x`。代码的解释可能需要斟酌一下
---

**Comment by ZhangHanDong** [comment]
@yim7 感谢反馈，我抽空再确认下

**Comment by ZhangHanDong** [comment]
@yim7 刚才看了下，其实那句话是想表达：

「“如果复合结构本身实现了 Drop，则会（先）调用它自己的析构函数，（然后再调用其成员的析构函数）；否则，会（直接）调用其成员的析构函数”」

不过这些省略可能容易引起误会，我还是修正一下吧。感谢反馈。

**Comment by ZhangHanDong** [comment]
@yim

break那个示例，举的不太好。我重新换一个。

```rust

fn main() {
    let mut x: i32 = 0;
    let y =  loop {
        x += 1;
        if x > 5 {
            let y = x;
            break y;
        }
    };
    println!("{}", y); 
}
```
